### ISSUE TITLE
Module Not found rich.theme

### ISSUE THREAD

**Issue by duskfallcrew** [bmaltais/kohya_ss#1040]
For reference I used this: https://github.com/15ky3/kohya-vast-installer
And i'm ssh'ed into a console for an RTX 3090.
Should i give up and just start going to runpod for lora training and then use vast for SD? LOL

When i used the "UNINSTALL" freeze command i diotically then uninstalled conda -- so i can't go back and try and fix it on THIS INSTANCE SPECIFICALLY.

if  anything, i think on vast there's a permissions isssue, because i don't think there's ANYTHING missing?

**Comment by bmaltais** [comment]
Good question. I have started to update the setup for linux based system. I don't use most of those solutions so the setup is not great... but if you know of specific installations steps for a given platform and share them I can probably integrate it... as long as it use a similar approach (venv and not conda) as the rest. For example, specific python modules needed to make things work, etc.

**Comment by kieranxsomer** [comment]
Yea sadly their SSH and jupyter won't let me VENV, at all - despite it being a thing in python (like look i've installed this locally on my imac 2019, it's just -- I can't TRAIN anything causei 'm on an AMD machine, and also i suppose lol - it's probably somewhat faster than colab's been LOL) - but it's WEIRD like i go to command "VENV" cause i'm aware of it from using a LITTLE of advanced toys like this --

Because i installed A1111 locally on my potato MBP (trust me it's one of the keyboard does not want to stay attached models, that's more than potato if not offensive to potato machinese lol) - sure as heck it barely works if not crashesp ython, but i can at least venv !

I'm not SURE WHY i can't venv on there.
I'll look at runpod tomorrow, look i'm happy if ONE OF THE TWO services works - if RUNPOD's template works, and i'm only training lora, that's totally fine, evne training models is easy enough at runpod - i've only had it super buggy when i'm trying to do model MERGING and it randomly quits on me, (* not kohya) - so that' was why i'd swapped to vast.

I've been using kohya-ss scripts via. custom colab notebooks but i'm DESPERATE now to move off colab because the T4's are slowed to a halt because of google's mess.

(Also, i uhhhh think i met you via discord and dogu cat just about SLAPPED me because i didn't know it was you -if that indeed was you i owe the sincerest of apologies in the civit discord lol)

**Comment by bmaltais** [comment]
I have pushed an updated setup.sh script to the dev2 branch... you may want to try it out with `git checkout dev2`

It still requires a venv I think... not sure what would be required to fix that for runpod...

**Comment by kieranxsomer** [comment]
UnimplementedError: Exception encountered when calling layer 'root_conv2d' (type was the error i got this time on runpod lmao i'm swapping back to manually installing on vast XD - sometimes complicated multisetups fail miserably - and i'm aware that exeception was tensorboard failing for some weird reason - i don't think it's Kohya-ss as more someting to do with the tensorboard that was installed WITH the setup i was using.
 
 Will comment back and if i'm still getting certain errors, it MAY not be your code anymore it's likely that some reason tehy don't do venv on either runpod or otherwise and MAYBE if i'm lucky i can get rich and get a new computer *GIGGLE*

**Comment by kieranxsomer** [comment]
Ok in stating: the thing DOES SWAP to a virtual environment but i can't manually go to a venv, so i'm manually installing your way instead of the vast sh because yours lets me get as far as using the tagger which is a lot faster than setting up colab and waiting to press 30 buttons ;)

**Comment by kieranxsomer** [comment]
Ok right now lmao it's doing this: root@(VAST AI SSH DETAILS DELETED FOR WHATEVER DORKY REASON I DUNNO IF ITS IMPROTANT OR NOT XD ) : ~/kohya_ss$ bash gui.sh --share
gui.sh: line 34: /root/kohya_ss/venv/bin/activate: No such file or directory

XD i'm going to adhoc a couple more things, see if i made a mistake :3

**Comment by kieranxsomer** [comment]
Ok for now i'm gonna pause trying to get it to work on either runpod OR vast, so i do'nt keep trying to waste my credits *for now* and i'll wait a bit until the dev branches are fixed <3 

I was havintg the display error one happen again because i couldn't get the dev branch to come back when i reinstalled it - and i shoudl've just trashed and re-done my instance. . but i just .. XD I am very easily frustrated, and i'd rather try and be patient.

good things can't be rushed!

**Comment by bmaltais** [comment]
Not sure why it won't work for you on runpod. I just pushed an update that I tested on it and it sort of worked... with some tensorrt errors but worked none the less.

**Comment by kieranxsomer** [comment]
AH! Yea runpod gave me weird tensor errors but i was also using a custom template rather than using a straight jupyter notebook.

Honestly i've had weird headaches all weekend so i'm happy just patiently waiting and then trying to get my brain to stop stabbing itself LOL.

I'm the kinda dork with my ADHD and othe things that will spend 6+ hours trying to figure it out even if i don't understand it.

i'll check it out again tomorrow or tues :3
