### ISSUE TITLE
I get an issue when i try to train the Model, What should i do now? (Error caught was: No module named 'triton') (train_network.py FAILED)

### ISSUE THREAD

**Issue by pkdude** [bmaltais/kohya_ss#1056]
It gives these error messages:

WARNING  NOTE: Redirects are currently not supported in Windows or MacOs.                     redirects.py:27
[W ..\torch\csrc\distributed\c10d\socket.cpp:601] [c10d] The client socket has failed to connect to [DESKTOP-1FO5]:29500 (system error: 10049 - The requested address is not valid in its context.).
[W ..\torch\csrc\distributed\c10d\socket.cpp:601] [c10d] The client socket has failed to connect to [DESKTOP-1FO5]:29500 (system error: 10049 - The requested address is not valid in its context.).

Error caught was: No module named 'triton'

RuntimeError: Distributed package doesn't have NCCL built in
[04:16:44] ERROR    failed (exitcode: 1) local_rank: 0 (pid: 3204) of binary:                                 api.py:672
                    H:\A1111\kohya_ss\venv\Scripts\python.exe

train_network.py FAILED

**Comment by FlareP1** [comment]
I have the same problem, was just trying to update from an older version.  Have do a complete reinstall and using torch2.  Oh Windows10 OS

C:\Users\Chris\Documents\kohya_ss>gui
12:45:28-884438 INFO     Version: ba26879 Sat Jun 24 06:51:44 2023 -0400
12:45:28-888437 INFO     nVidia toolkit detected
12:45:29-944437 INFO     Torch 2.0.1+cu118
12:45:29-953437 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8700
12:45:29-955437 INFO     Torch detected GPU: NVIDIA GeForce RTX 3080 VRAM 10240 Arch (8, 6) Cores 68
12:45:29-956437 INFO     Verifying modules instalation status from requirements_windows_torch2.txt...
12:45:29-959438 INFO     Verifying modules instalation status from requirements.txt...
12:45:31-502437 INFO     headless: False
12:45:31-505439 INFO     Load CSS...
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.

I get the same error, I did notice that the application asked for network access via the windows firewall the firsttime I ran it which I refused.  Not sure if this has somethig to do with the issue.  I did not expect that it would need network access, but it is trying to access the local machine via its netbios name and port 29500.

[W ..\torch\csrc\distributed\c10d\socket.cpp:601] [c10d] The client socket has failed to connect to [i12-Machine]:29500 (system error: 10049 - unknown error).
[W ..\torch\csrc\distributed\c10d\socket.cpp:601] [c10d] The client socket has failed to connect to [i12-Machine]:29500 (system error: 10049 - unknown error).
RuntimeError: Distributed package doesn't have NCCL built in
ChildFailedError:
============================================================
train_network.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-06-24_12:47:31
  host      : i12-Machine
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 9604)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

**Comment by bmaltais** [comment]
I suspect wathever it was refused access to might be the issue. Allow all access, delete the bench and redo the setup.

**Comment by FlareP1** [comment]
Ok I fixed my issue, it was becuase I was selecting the multi-GPU issue in Accelerate, if I only select no distributed training then it works correctly.  Changing the firewall did not appear to fix the issue.

`------------------------------------------------------------------------------------------------------------------------In which compute environment are you running?
This machine
------------------------------------------------------------------------------------------------------------------------Which type of machine are you using?
Please select a choice using the arrow or number keys, and selecting with enter
 * No distributed training
    multi-CPU
    multi-GPU
    TPU
    MPS`

**Comment by pkdude** [comment]
> I have the same problem, was just trying to update from an older version. Have do a complete reinstall and using torch2. Oh Windows10 OS
> 
> C:\Users\Chris\Documents\kohya_ss>gui 12:45:28-884438 INFO Version: [ba26879](https://github.com/bmaltais/kohya_ss/commit/ba268796634dce6e21135805a015304aa603a7f6) Sat Jun 24 06:51:44 2023 -0400 12:45:28-888437 INFO nVidia toolkit detected 12:45:29-944437 INFO Torch 2.0.1+cu118 12:45:29-953437 INFO Torch backend: nVidia CUDA 11.8 cuDNN 8700 12:45:29-955437 INFO Torch detected GPU: NVIDIA GeForce RTX 3080 VRAM 10240 Arch (8, 6) Cores 68 12:45:29-956437 INFO Verifying modules instalation status from requirements_windows_torch2.txt... 12:45:29-959438 INFO Verifying modules instalation status from requirements.txt... 12:45:31-502437 INFO headless: False 12:45:31-505439 INFO Load CSS... Running on local URL: http://127.0.0.1:7860
> 
> To create a public link, set `share=True` in `launch()`.
> 
> I get the same error, I did notice that the application asked for network access via the windows firewall the firsttime I ran it which I refused. Not sure if this has somethig to do with the issue. I did not expect that it would need network access, but it is trying to access the local machine via its netbios name and port 29500.
> 
> ```
> 
> [W ..\torch\csrc\distributed\c10d\socket.cpp:601] [c10d] The client socket has failed to connect to [i12-Machine]:29500 (system error: 10049 - unknown error).
> [W ..\torch\csrc\distributed\c10d\socket.cpp:601] [c10d] The client socket has failed to connect to [i12-Machine]:29500 (system error: 10049 - unknown error).
> RuntimeError: Distributed package doesn't have NCCL built in
> ChildFailedError:
> ============================================================
> train_network.py FAILED
> ------------------------------------------------------------
> Failures:
>   <NO_OTHER_FAILURES>
> ------------------------------------------------------------
> Root Cause (first observed failure):
> [0]:
>   time      : 2023-06-24_12:47:31
>   host      : i12-Machine
>   rank      : 0 (local_rank: 0)
>   exitcode  : 1 (pid: 9604)
>   error_file: <N/A>
>   traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
> ============================================================
> ```

I tired everything.. but it didn't work me..
I feel the same, that network access notification might be the issue. I have to try. But, how should i go back and change that?
