### ISSUE TITLE
Using a conda env instead of venv

### ISSUE THREAD

**Issue by lopezjuanma96** [bmaltais/kohya_ss#1088]
Hi, is there a way I can setup repo to run from a conda environment instead of creating `venv`? I'm running on a limited linux server and cannot change the Python version to > 3.10.6 ... I tried creating the environment and installing `requirements_linux.txt` but I get the error: 
```
ERROR: Invalid requirement: 'torch==2.0.1+cu118 torchvision==0.15.2+cu118' (from line 1 of requirements_linux.txt)
```
And although i can install the requirements.txt I still get errors when running gui.sh

**Comment by bmaltais** [comment]
Technically you could install everything in conda and the use

python kohya_gui.py to start the GUI... That would allow you to run without using a venv

**Comment by bmaltais** [comment]
Hummm... Maybe not... I think some of the scripts might actually point to a local venv folder... I am not sure...

**Comment by lopezjuanma96** [comment]
Thanks for the quick response, I'm AFK right now but I'll test again tomorrow, would you mind if I sent you what issues I come up against here while I try doing that?

**Comment by bmaltais** [comment]
Try starting the GUI with: `python kohya_gui.py --headless`

**Comment by lopezjuanma96** [comment]
**UPDATE:**

I was able to run `kohya_gui.py` without the headless parameter by properly refering to the venv python. For some reason the server I was using was using the conda environment by default, even with an independent python installation, probably something to do with th `~/.bashrc` initialization. In any case, I was able to run it using `venv/bin/python kohya_gui.py` (venv refering obviously to the venv created un the setup execution).

As for the 'tpu_env' error I followed some instructions on #564 and modified the default accelerate configuration YAML file at `~/.cache/huggingface/accelerate/default_config.yaml`. This could have probably be avoided by configurationg accelerate manually with `venv/bin/accelerate config` but it was raising errors on my end on the configuration process, might work for someone else.

**Comment by ballerburg9005** [comment]
I am on Archlinux, so my python version is 3.11.8 and using conda can fix this.

So I did this to make it run:

```
conda create -n kohya python=3.10.9
conda activate kohya
conda install pylint-venv
pip install -r requirements.txt

pip install xformers
pip install bitsandbytes

python kohya_gui.py --headless
```

**Comment by Nixellion** [comment]
Yeah, IMO, all AI\ML projects should start using conda by default, because of all the version incompatibilities between python, torch, cuda, etc. Without using conda it's practically impossible to install 2 AI projects that use different versions of cuda, for example. Even with venv it's complicated. I don't think you can have both 11.x and 12.x CUDA versions installed on one system. And even on servers, spamming containers for every task is often tedious.

Conda serves all of these problems in a few lines. I don't understand why people spend so much time writing complicated bash install scripts, when 90% of that code - a few conda commands can solve it. Literally @ballerburg9005 just showed all the commands one has to run to install it. And it's completely system agnostic, it will work on windows and linux alike. Not sure about MacOS, probably as well. So you just need to install miniconda, then these commands.

And miniconda is there as well, you don't need to install the full fat anaconda.

I didn't like it myself at first, did not understand the benefits, but now I definitely do.

@ballerburg9005 thanks for the commands. I would however use `python -m pip install ...` just to be safe and make sure the correct python and pip are used. 

You also need to install cuda though, and requirements_linux have torch install lines that dont work, so full set for me is:

```
# Install miniconda as per https://docs.anaconda.com/miniconda/
git clone --recursive https://github.com/bmaltais/kohya_ss.git
cd kohya_ss
conda create -n kohya python=3.10.9
conda activate kohya
conda install pylint-venv
conda install -y -c "nvidia/label/cuda-11.8.0" cuda
python -m pip install torch==2.1.2+cu118 torchvision==0.16.2+cu118 xformers==0.0.23.post1+cu118 --extra-index-url https://download.pytorch.org/whl/cu118
pip install -r requirements.txt
python -m pip install xformers bitsandbytes
```

It launched. Did not yet try training anything with it, will do soon.
