### ISSUE TITLE
Error when i try training

### ISSUE THREAD

**Issue by Voltayn** [bmaltais/kohya_ss#1146]
i got somethin like
prepare tokenizer
Using DreamBooth method.
prepare images.
found directory C:\Users\Admin\Desktop\Keran LorA\image\137_Keran contains 11 image files
1507 train images with repeating.
0 reg images.
no regularization images / 正則化画像が見つかりませんでした
[Dataset 0]
  batch_size: 2
  resolution: (512, 512)
  enable_bucket: False

  [Subset 0 of Dataset 0]
    image_dir: "C:\Users\Admin\Desktop\Keran LorA\image\137_Keran"
    image_count: 11
    num_repeats: 137
    shuffle_caption: False
    keep_tokens: 0
    caption_dropout_rate: 0.0
    caption_dropout_every_n_epoches: 0
    caption_tag_dropout_rate: 0.0
    color_aug: False
    flip_aug: False
    face_crop_aug_range: None
    random_crop: False
    token_warmup_min: 1,
    token_warmup_step: 0,
    is_reg: False
    class_tokens: Keran
    caption_extension: .txt

[Dataset 0]
loading image sizes.
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 11/11 [00:00<00:00, 1571.54it/s]
prepare dataset
preparing accelerator
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ D:\IA\SD\Khoya\kohya_ss\train_network.py:974 in <module>                                         │
│                                                                                                  │
│   971 │   args = train_util.read_config_from_file(args, parser)                                  │
│   972 │                                                                                          │
│   973 │   trainer = NetworkTrainer()                                                             │
│ ❱ 974 │   trainer.train(args)                                                                    │
│   975                                                                                            │
│                                                                                                  │
│ D:\IA\SD\Khoya\kohya_ss\train_network.py:205 in train                                            │
│                                                                                                  │
│   202 │   │                                                                                      │
│   203 │   │   # acceleratorを準備する                                                            │
│   204 │   │   print("preparing accelerator")                                                     │
│ ❱ 205 │   │   accelerator = train_util.prepare_accelerator(args)                                 │
│   206 │   │   is_main_process = accelerator.is_main_process                                      │
│   207 │   │                                                                                      │
│   208 │   │   # mixed precisionに対応した型を用意しておき適宜castする                            │
│                                                                                                  │
│ D:\IA\SD\Khoya\kohya_ss\library\train_util.py:3266 in prepare_accelerator                        │
│                                                                                                  │
│   3263 │   │   │   if args.wandb_api_key is not None:                                            │
│   3264 │   │   │   │   wandb.login(key=args.wandb_api_key)                                       │
│   3265 │                                                                                         │
│ ❱ 3266 │   accelerator = Accelerator(                                                            │
│   3267 │   │   gradient_accumulation_steps=args.gradient_accumulation_steps,                     │
│   3268 │   │   mixed_precision=args.mixed_precision,                                             │
│   3269 │   │   log_with=log_with,                                                                │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
TypeError: __init__() got an unexpected keyword argument 'project_dir'
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\runpy.py:197 in _run_module_as_main    │
│                                                                                                  │
│   194 │   main_globals = sys.modules["__main__"].__dict__                                        │
│   195 │   if alter_argv:                                                                         │
│   196 │   │   sys.argv[0] = mod_spec.origin                                                      │
│ ❱ 197 │   return _run_code(code, main_globals, None,                                             │
│   198 │   │   │   │   │    "__main__", mod_spec)                                                 │
│   199                                                                                            │
│   200 def run_module(mod_name, init_globals=None,                                                │
│                                                                                                  │
│ C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\runpy.py:87 in _run_code               │
│                                                                                                  │
│    84 │   │   │   │   │      __loader__ = loader,                                                │
│    85 │   │   │   │   │      __package__ = pkg_name,                                             │
│    86 │   │   │   │   │      __spec__ = mod_spec)                                                │
│ ❱  87 │   exec(code, run_globals)                                                                │
│    88 │   return run_globals                                                                     │
│    89                                                                                            │
│    90 def _run_module_code(code, init_globals=None,                                              │
│                                                                                                  │
│ in <module>:7                                                                                    │
│                                                                                                  │
│   4 from accelerate.commands.accelerate_cli import main                                          │
│   5 if __name__ == '__main__':                                                                   │
│   6 │   sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])                         │
│ ❱ 7 │   sys.exit(main())                                                                         │
│   8                                                                                              │
│                                                                                                  │
│ D:\IA\SD\Khoya\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py:45 in main  │
│                                                                                                  │
│   42 │   │   exit(1)                                                                             │
│   43 │                                                                                           │
│   44 │   # Run                                                                                   │
│ ❱ 45 │   args.func(args)                                                                         │
│   46                                                                                             │
│   47                                                                                             │
│   48 if __name__ == "__main__":                                                                  │
│                                                                                                  │
│ D:\IA\SD\Khoya\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py:1104 in             │
│ launch_command                                                                                   │
│                                                                                                  │
│   1101 │   elif defaults is not None and defaults.compute_environment == ComputeEnvironment.AMA  │
│   1102 │   │   sagemaker_launcher(defaults, args)                                                │
│   1103 │   else:                                                                                 │
│ ❱ 1104 │   │   simple_launcher(args)                                                             │
│   1105                                                                                           │
│   1106                                                                                           │
│   1107 def main():                                                                               │
│                                                                                                  │
│ D:\IA\SD\Khoya\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py:567 in              │
│ simple_launcher                                                                                  │
│                                                                                                  │
│    564 │   process = subprocess.Popen(cmd, env=current_env)                                      │
│    565 │   process.wait()                                                                        │
│    566 │   if process.returncode != 0:                                                           │
│ ❱  567 │   │   raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)       │
│    568                                                                                           │
│    569                                                                                           │
│    570 def multi_gpu_launcher(args):                                                             │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
CalledProcessError: Command '['D:\\IA\\SD\\Khoya\\kohya_ss\\venv\\Scripts\\python.exe', './train_network.py',
'--pretrained_model_name_or_path=D:/IA/SD/stable-diffusion-webui/models/Stable-diffusion/realisticVisionV30_v30VAE.safetensors', '--train_data_dir=C:/Users/Admin/Desktop/Keran LorA/image', '--resolution=512,512',
'--output_dir=C:/Users/Admin/Desktop/Keran LorA/model', '--logging_dir=C:/Users/Admin/Desktop/Keran LorA/log', '--network_alpha=128', '--save_model_as=safetensors', '--network_module=networks.lora', '--text_encoder_lr=5e-05',
'--unet_lr=0.0001', '--network_dim=128', '--output_name=Keran', '--lr_scheduler_num_cycles=1', '--learning_rate=0.0001', '--lr_scheduler=constant', '--train_batch_size=2', '--max_train_steps=754', '--save_every_n_epochs=1',
'--mixed_precision=bf16', '--save_precision=bf16', '--seed=1234', '--caption_extension=.txt', '--cache_latents', '--optimizer_type=AdamW8bit', '--max_data_loader_n_workers=1', '--clip_skip=2', '--bucket_reso_steps=64', '--xformers',
'--bucket_no_upscale']' returned non-zero exit status 1.

**Comment by JaredS215** [comment]
Seeing the same error in WSL2 Ubuntu.  Tried deleting the venv and reinstalling packages and no luck.

**Comment by HairyPortal** [comment]
Same error in runpod.

**Comment by ManglerFTW** [comment]
I had a similar issue in collab. But instead of "TypeError: init() got an unexpected keyword argument 'project_dir'" it was "TypeError: accelerate_init() got an unexpected keyword argument 'project_dir'". Tried a newer version of of accelerate, but it didn't change the result.

**Comment by Voltayn** [comment]
> I had a similar issue in colab. But instead of "TypeError: init() got an unexpected keyword argument 'project_dir'" it was "TypeError: accelerate_init() got an unexpected keyword argument 'project_dir'". Tried a newer version of of accelerate, but it didn't change the result.

i solved the problem, first i installed Python 3.10.9 instead of 3.11 then i uninstalled every khoya files, and i relaunched setup.bat but this time i installed torch 2 and it worked

**Comment by JaredS215** [comment]
I wonder if it is caused by the interaction of https://github.com/bmaltais/kohya_ss/commit/0315611b11c92ab7ad60ac82bf285d8461b78910 and https://github.com/bmaltais/kohya_ss/commit/73cc00ec274bfc3a529e4a2bd13c4f9f859ce2b5

I think this was the last commit I was using that worked https://github.com/bmaltais/kohya_ss/tree/0fe2df79b54c6b60381ad1aead2e89330cfa7154

**Comment by YmanChris** [comment]
> I wonder if it is caused by the interaction of [0315611](https://github.com/bmaltais/kohya_ss/commit/0315611b11c92ab7ad60ac82bf285d8461b78910) and [73cc00e](https://github.com/bmaltais/kohya_ss/commit/73cc00ec274bfc3a529e4a2bd13c4f9f859ce2b5)
> 
> I think this was the last commit I was using that worked https://github.com/bmaltais/kohya_ss/tree/0fe2df79b54c6b60381ad1aead2e89330cfa7154

same problem, online watching....

**Comment by YmanChris** [comment]
> I wonder if it is caused by the interaction of [0315611](https://github.com/bmaltais/kohya_ss/commit/0315611b11c92ab7ad60ac82bf285d8461b78910) and [73cc00e](https://github.com/bmaltais/kohya_ss/commit/73cc00ec274bfc3a529e4a2bd13c4f9f859ce2b5)
> 
> I think this was the last commit I was using that worked https://github.com/bmaltais/kohya_ss/tree/0fe2df79b54c6b60381ad1aead2e89330cfa7154

I update accelerate version==0.19.0 in requirements_linux.txt and re execute ./setup.sh, It works in wsl2.

**Comment by bmaltais** [comment]
Hummmm, yeah, the accelerate version might be the cause... Weird that it work on my system. Let me check what accelerate version I use...

**Comment by bmaltais** [comment]
OK, apparently the accelerate 0.15.0 is no longer working with the new sd-scripts code... I have uploaded a fix. Do a git pull and try it again. Try using torch 2 also instead of torch 1 if that is what you use. Torch 1 is on it's last leg.

**Comment by JaredS215** [comment]
It now works with 0.19.0.  Thank you!

**Comment by OurPresenceKai** [comment]
prepare tokenizer
prepare images.
found directory H:\AI\Lora\output\spider\image\60_spider_style contains 75 image files
4500 train images with repeating.
0 reg images.
no regularization images / 正則化画像が見つかりませんでした
[Dataset 0]
  batch_size: 2
  resolution: (910, 512)
  enable_bucket: False

  [Subset 0 of Dataset 0]
    image_dir: "H:\AI\Lora\output\spider\image\60_spider_style"
    image_count: 75
    num_repeats: 60
    shuffle_caption: False
    keep_tokens: 0
    caption_dropout_rate: 0.0
    caption_dropout_every_n_epoches: 0
    caption_tag_dropout_rate: 0.0
    color_aug: False
    flip_aug: False
    face_crop_aug_range: None
    random_crop: False
    token_warmup_min: 1,
    token_warmup_step: 0,
    is_reg: False
    class_tokens: spider_style
    caption_extension: .txt


[Dataset 0]
loading image sizes.
100%|████████████████████████████████████████████████████████████████████████████████| 75/75 [00:00<00:00, 4421.45it/s]
prepare dataset
prepare accelerator
loading model for process 0/1
load StableDiffusion checkpoint: H:/AI/Stable-Diffusion/stable-diffusion-webui/models/Stable-diffusion/oukaNiji5_v10.safetensors
UNet2DConditionModel: 64, 8, 768, False, False
loading u-net: <All keys matched successfully>
loading vae: <All keys matched successfully>
loading text encoder: <All keys matched successfully>
Enable xformers for U-Net
[Dataset 0]
caching latents.
100%|██████████████████████████████████████████████████████████████████████████████████| 75/75 [00:09<00:00,  8.18it/s]
prepare optimizer, data loader etc.

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
For effortless bug reporting copy-paste your error into this form: https://docs.google.com/forms/d/e/1FAIpQLScPB8emS3Thkp66nvqwmjTEgxp8Y9ufuWTzFyr9kJ5AoI47dQ/viewform?usp=sf_link
================================================================================
CUDA SETUP: Loading binary H:\AI\kohya_ss\kohya_ss\venv\lib\site-packages\bitsandbytes\libbitsandbytes_cuda116.dll...
use 8-bit AdamW optimizer | {}
running training / 学習開始
  num train images * repeats / 学習画像の数×繰り返し回数: 4500
  num reg images / 正則化画像の数: 0
  num batches per epoch / 1epochのバッチ数: 2250
  num epochs / epoch数: 3
  batch size per device / バッチサイズ: 2
  total train batch size (with parallel & distributed & accumulation) / 総バッチサイズ（並列学習、勾配合計含む）: 2
  gradient ccumulation steps / 勾配を合計するステップ数 = 1
  total optimization steps / 学習ステップ数: 6750
steps:   0%|                                                                                  | 0/6750 [00:00<?, ?it/s]
epoch 1/3
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ H:\AI\kohya_ss\kohya_ss\train_db.py:474 in <module>                                              │
│                                                                                                  │
│   471 │   args = parser.parse_args()                                                             │
│   472 │   args = train_util.read_config_from_file(args, parser)                                  │
│   473 │                                                                                          │
│ ❱ 474 │   train(args)                                                                            │
│   475                                                                                            │
│                                                                                                  │
│ H:\AI\kohya_ss\kohya_ss\train_db.py:307 in train                                                 │
│                                                                                                  │
│   304 │   │   │   │                                                                              │
│   305 │   │   │   │   # Predict the noise residual                                               │
│   306 │   │   │   │   with accelerator.autocast():                                               │
│ ❱ 307 │   │   │   │   │   noise_pred = unet(noisy_latents, timesteps, encoder_hidden_states).s   │
│   308 │   │   │   │                                                                              │
│   309 │   │   │   │   if args.v_parameterization:                                                │
│   310 │   │   │   │   │   # v-parameterization training                                          │
│                                                                                                  │
│ H:\AI\kohya_ss\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py:1130 in _call_impl     │
│                                                                                                  │
│   1127 │   │   # this function, and just call forward.                                           │
│   1128 │   │   if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks o  │
│   1129 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                   │
│ ❱ 1130 │   │   │   return forward_call(*input, **kwargs)                                         │
│   1131 │   │   # Do not call functions when jit is used                                          │
│   1132 │   │   full_backward_hooks, non_full_backward_hooks = [], []                             │
│   1133 │   │   if self._backward_hooks or _global_backward_hooks:                                │
│                                                                                                  │
│ H:\AI\kohya_ss\kohya_ss\venv\lib\site-packages\accelerate\utils\operations.py:521 in forward     │
│                                                                                                  │
│   518 │   model_forward = ConvertOutputsToFp32(model_forward)                                    │
│   519 │                                                                                          │
│   520 │   def forward(*args, **kwargs):                                                          │
│ ❱ 521 │   │   return model_forward(*args, **kwargs)                                              │
│   522 │                                                                                          │
│   523 │   # To act like a decorator so that it can be popped when doing `extract_model_from_pa   │
│   524 │   forward.__wrapped__ = model_forward                                                    │
│                                                                                                  │
│ H:\AI\kohya_ss\kohya_ss\venv\lib\site-packages\accelerate\utils\operations.py:509 in __call__    │
│                                                                                                  │
│   506 │   │   update_wrapper(self, model_forward)                                                │
│   507 │                                                                                          │
│   508 │   def __call__(self, *args, **kwargs):                                                   │
│ ❱ 509 │   │   return convert_to_fp32(self.model_forward(*args, **kwargs))                        │
│   510 │                                                                                          │
│   511 │   def __getstate__(self):                                                                │
│   512 │   │   raise pickle.PicklingError(                                                        │
│                                                                                                  │
│ H:\AI\kohya_ss\kohya_ss\venv\lib\site-packages\torch\amp\autocast_mode.py:12 in                  │
│ decorate_autocast                                                                                │
│                                                                                                  │
│     9 │   @functools.wraps(func)                                                                 │
│    10 │   def decorate_autocast(*args, **kwargs):                                                │
│    11 │   │   with autocast_instance:                                                            │
│ ❱  12 │   │   │   return func(*args, **kwargs)                                                   │
│    13 │   decorate_autocast.__script_unsupported = '@autocast() decorator is not supported in    │
│    14 │   return decorate_autocast                                                               │
│    15                                                                                            │
│                                                                                                  │
│ H:\AI\kohya_ss\kohya_ss\library\original_unet.py:1565 in forward                                 │
│                                                                                                  │
│   1562 │   │   │   │   upsample_size = down_block_res_samples[-1].shape[2:]                      │
│   1563 │   │   │                                                                                 │
│   1564 │   │   │   if upsample_block.has_cross_attention:                                        │
│ ❱ 1565 │   │   │   │   sample = upsample_block(                                                  │
│   1566 │   │   │   │   │   hidden_states=sample,                                                 │
│   1567 │   │   │   │   │   temb=emb,                                                             │
│   1568 │   │   │   │   │   res_hidden_states_tuple=res_samples,                                  │
│                                                                                                  │
│ H:\AI\kohya_ss\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py:1130 in _call_impl     │
│                                                                                                  │
│   1127 │   │   # this function, and just call forward.                                           │
│   1128 │   │   if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks o  │
│   1129 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                   │
│ ❱ 1130 │   │   │   return forward_call(*input, **kwargs)                                         │
│   1131 │   │   # Do not call functions when jit is used                                          │
│   1132 │   │   full_backward_hooks, non_full_backward_hooks = [], []                             │
│   1133 │   │   if self._backward_hooks or _global_backward_hooks:                                │
│                                                                                                  │
│ H:\AI\kohya_ss\kohya_ss\library\original_unet.py:1243 in forward                                 │
│                                                                                                  │
│   1240 │   │   │   │   )[0]                                                                      │
│   1241 │   │   │   else:                                                                         │
│   1242 │   │   │   │   hidden_states = resnet(hidden_states, temb)                               │
│ ❱ 1243 │   │   │   │   hidden_states = attn(hidden_states, encoder_hidden_states=encoder_hidden  │
│   1244 │   │                                                                                     │
│   1245 │   │   if self.upsamplers is not None:                                                   │
│   1246 │   │   │   for upsampler in self.upsamplers:                                             │
│                                                                                                  │
│ H:\AI\kohya_ss\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py:1130 in _call_impl     │
│                                                                                                  │
│   1127 │   │   # this function, and just call forward.                                           │
│   1128 │   │   if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks o  │
│   1129 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                   │
│ ❱ 1130 │   │   │   return forward_call(*input, **kwargs)                                         │
│   1131 │   │   # Do not call functions when jit is used                                          │
│   1132 │   │   full_backward_hooks, non_full_backward_hooks = [], []                             │
│   1133 │   │   if self._backward_hooks or _global_backward_hooks:                                │
│                                                                                                  │
│ H:\AI\kohya_ss\kohya_ss\library\original_unet.py:875 in forward                                  │
│                                                                                                  │
│    872 │   │                                                                                     │
│    873 │   │   # 2. Blocks                                                                       │
│    874 │   │   for block in self.transformer_blocks:                                             │
│ ❱  875 │   │   │   hidden_states = block(hidden_states, context=encoder_hidden_states, timestep  │
│    876 │   │                                                                                     │
│    877 │   │   # 3. Output                                                                       │
│    878 │   │   if not self.use_linear_projection:                                                │
│                                                                                                  │
│ H:\AI\kohya_ss\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py:1130 in _call_impl     │
│                                                                                                  │
│   1127 │   │   # this function, and just call forward.                                           │
│   1128 │   │   if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks o  │
│   1129 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                   │
│ ❱ 1130 │   │   │   return forward_call(*input, **kwargs)                                         │
│   1131 │   │   # Do not call functions when jit is used                                          │
│   1132 │   │   full_backward_hooks, non_full_backward_hooks = [], []                             │
│   1133 │   │   if self._backward_hooks or _global_backward_hooks:                                │
│                                                                                                  │
│ H:\AI\kohya_ss\kohya_ss\library\original_unet.py:804 in forward                                  │
│                                                                                                  │
│    801 │   │   hidden_states = self.attn2(norm_hidden_states, context=context) + hidden_states   │
│    802 │   │                                                                                     │
│    803 │   │   # 3. Feed-forward                                                                 │
│ ❱  804 │   │   hidden_states = self.ff(self.norm3(hidden_states)) + hidden_states                │
│    805 │   │                                                                                     │
│    806 │   │   return hidden_states                                                              │
│    807                                                                                           │
│                                                                                                  │
│ H:\AI\kohya_ss\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py:1130 in _call_impl     │
│                                                                                                  │
│   1127 │   │   # this function, and just call forward.                                           │
│   1128 │   │   if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks o  │
│   1129 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                   │
│ ❱ 1130 │   │   │   return forward_call(*input, **kwargs)                                         │
│   1131 │   │   # Do not call functions when jit is used                                          │
│   1132 │   │   full_backward_hooks, non_full_backward_hooks = [], []                             │
│   1133 │   │   if self._backward_hooks or _global_backward_hooks:                                │
│                                                                                                  │
│ H:\AI\kohya_ss\kohya_ss\library\original_unet.py:750 in forward                                  │
│                                                                                                  │
│    747 │                                                                                         │
│    748 │   def forward(self, hidden_states):                                                     │
│    749 │   │   for module in self.net:                                                           │
│ ❱  750 │   │   │   hidden_states = module(hidden_states)                                         │
│    751 │   │   return hidden_states                                                              │
│    752                                                                                           │
│    753                                                                                           │
│                                                                                                  │
│ H:\AI\kohya_ss\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py:1130 in _call_impl     │
│                                                                                                  │
│   1127 │   │   # this function, and just call forward.                                           │
│   1128 │   │   if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks o  │
│   1129 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                   │
│ ❱ 1130 │   │   │   return forward_call(*input, **kwargs)                                         │
│   1131 │   │   # Do not call functions when jit is used                                          │
│   1132 │   │   full_backward_hooks, non_full_backward_hooks = [], []                             │
│   1133 │   │   if self._backward_hooks or _global_backward_hooks:                                │
│                                                                                                  │
│ H:\AI\kohya_ss\kohya_ss\library\original_unet.py:728 in forward                                  │
│                                                                                                  │
│    725 │   │   return F.gelu(gate.to(dtype=torch.float32)).to(dtype=gate.dtype)                  │
│    726 │                                                                                         │
│    727 │   def forward(self, hidden_states):                                                     │
│ ❱  728 │   │   hidden_states, gate = self.proj(hidden_states).chunk(2, dim=-1)                   │
│    729 │   │   return hidden_states * self.gelu(gate)                                            │
│    730                                                                                           │
│    731                                                                                           │
│                                                                                                  │
│ H:\AI\kohya_ss\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py:1130 in _call_impl     │
│                                                                                                  │
│   1127 │   │   # this function, and just call forward.                                           │
│   1128 │   │   if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks o  │
│   1129 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                   │
│ ❱ 1130 │   │   │   return forward_call(*input, **kwargs)                                         │
│   1131 │   │   # Do not call functions when jit is used                                          │
│   1132 │   │   full_backward_hooks, non_full_backward_hooks = [], []                             │
│   1133 │   │   if self._backward_hooks or _global_backward_hooks:                                │
│                                                                                                  │
│ H:\AI\kohya_ss\kohya_ss\venv\lib\site-packages\torch\nn\modules\linear.py:114 in forward         │
│                                                                                                  │
│   111 │   │   │   init.uniform_(self.bias, -bound, bound)                                        │
│   112 │                                                                                          │
│   113 │   def forward(self, input: Tensor) -> Tensor:                                            │
│ ❱ 114 │   │   return F.linear(input, self.weight, self.bias)                                     │
│   115 │                                                                                          │
│   116 │   def extra_repr(self) -> str:                                                           │
│   117 │   │   return 'in_features={}, out_features={}, bias={}'.format(                          │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeError: CUDA out of memory. Tried to allocate 72.00 MiB (GPU 0; 10.00 GiB total capacity; 9.12 GiB already
allocated; 0 bytes free; 9.23 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting
max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
steps:   0%|                                                                                  | 0/6750 [00:08<?, ?it/s]
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ C:\Users\yukai\AppData\Local\Programs\Python\Python310\lib\runpy.py:196 in _run_module_as_main   │
│                                                                                                  │
│   193 │   main_globals = sys.modules["__main__"].__dict__                                        │
│   194 │   if alter_argv:                                                                         │
│   195 │   │   sys.argv[0] = mod_spec.origin                                                      │
│ ❱ 196 │   return _run_code(code, main_globals, None,                                             │
│   197 │   │   │   │   │    "__main__", mod_spec)                                                 │
│   198                                                                                            │
│   199 def run_module(mod_name, init_globals=None,                                                │
│                                                                                                  │
│ C:\Users\yukai\AppData\Local\Programs\Python\Python310\lib\runpy.py:86 in _run_code              │
│                                                                                                  │
│    83 │   │   │   │   │      __loader__ = loader,                                                │
│    84 │   │   │   │   │      __package__ = pkg_name,                                             │
│    85 │   │   │   │   │      __spec__ = mod_spec)                                                │
│ ❱  86 │   exec(code, run_globals)                                                                │
│    87 │   return run_globals                                                                     │
│    88                                                                                            │
│    89 def _run_module_code(code, init_globals=None,                                              │
│                                                                                                  │
│ in <module>:7                                                                                    │
│                                                                                                  │
│   4 from accelerate.commands.accelerate_cli import main                                          │
│   5 if __name__ == '__main__':                                                                   │
│   6 │   sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])                         │
│ ❱ 7 │   sys.exit(main())                                                                         │
│   8                                                                                              │
│                                                                                                  │
│ H:\AI\kohya_ss\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py:45 in main  │
│                                                                                                  │
│   42 │   │   exit(1)                                                                             │
│   43 │                                                                                           │
│   44 │   # Run                                                                                   │
│ ❱ 45 │   args.func(args)                                                                         │
│   46                                                                                             │
│   47                                                                                             │
│   48 if __name__ == "__main__":                                                                  │
│                                                                                                  │
│ H:\AI\kohya_ss\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py:918 in              │
│ launch_command                                                                                   │
│                                                                                                  │
│   915 │   elif defaults is not None and defaults.compute_environment == ComputeEnvironment.AMA   │
│   916 │   │   sagemaker_launcher(defaults, args)                                                 │
│   917 │   else:                                                                                  │
│ ❱ 918 │   │   simple_launcher(args)                                                              │
│   919                                                                                            │
│   920                                                                                            │
│   921 def main():                                                                                │
│                                                                                                  │
│ H:\AI\kohya_ss\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py:580 in              │
│ simple_launcher                                                                                  │
│                                                                                                  │
│   577 │   process.wait()                                                                         │
│   578 │   if process.returncode != 0:                                                            │
│   579 │   │   if not args.quiet:                                                                 │
│ ❱ 580 │   │   │   raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)    │
│   581 │   │   else:                                                                              │
│   582 │   │   │   sys.exit(1)                                                                    │
│   583                                                                                            │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
CalledProcessError: Command '['H:\\AI\\kohya_ss\\kohya_ss\\venv\\Scripts\\python.exe', 'train_db.py',
'--pretrained_model_name_or_path=H:/AI/Stable-Diffusion/stable-diffusion-webui/models/Stable-diffusion/oukaNiji5_v10.saf
etensors', '--train_data_dir=H:/AI/Lora/output/spider/image', '--resolution=910,512',
'--output_dir=H:/AI/Lora/output/spider/model', '--logging_dir=H:/AI/Lora/output/spider/log',
'--save_model_as=safetensors', '--output_name=spider_style', '--max_data_loader_n_workers=1', '--learning_rate=0.0001',
'--lr_scheduler=cosine_with_restarts', '--lr_warmup_steps=675', '--train_batch_size=2', '--max_train_steps=6750',
'--save_every_n_epochs=1', '--mixed_precision=fp16', '--save_precision=fp16', '--seed=1234', '--caption_extension=.txt',
'--cache_latents', '--optimizer_type=AdamW8bit', '--max_data_loader_n_workers=1', '--bucket_reso_steps=64',
'--xformers', '--bucket_no_upscale']' returned non-zero exit status 1.

I have the same issue. It tells me this error when I try to train. It was working fine before the update.

**Comment by bmaltais** [comment]
Did you git pull the latest code? Did you install with torch 2?

**Comment by Norian11** [comment]
Thanks bmaltais with the new update it works as allways on runpod
