### ISSUE TITLE
Error: memory_efficient_attention() got an unexpected keyword argument 'scale'

### ISSUE THREAD

**Issue by Roadou** [bmaltais/kohya_ss#1155]
Hello,

I get this error when starting lora training.
I use torch 1, no deepspeed

log:
https://pastebin.com/ShxndA0c

**Comment by zymox** [comment]
I have the same issue. Stacktrace looks the same as well.

**Comment by zymox** [comment]
I think something got broken with accelerate in the recent commits. 

It works for me if instead of cloning the repo I download the second to last release https://github.com/bmaltais/kohya_ss/releases/tag/v21.7.16

With that one I couldn't press any buttons in the GUI, to fix that see: https://www.reddit.com/r/StableDiffusion/comments/14tkoa8/kohya_ss_help_cant_press_buttons/

**Comment by stoliucht** [comment]
same issue here

**Comment by NertonSaintfort** [comment]
I'm also getting the same issue

**Comment by secyunshu** [comment]
same.

**Comment by bmaltais** [comment]
Are you using the latest code with torch 2?
 I think I will drop torch 1 as it keep giving issues

**Comment by zymox** [comment]
I was using torch 1, as that was said to select in the tutorial I was following.

**Comment by NertonSaintfort** [comment]
> Are you using the latest code with torch 2? I think I will drop torch 1 as it keep giving issues

Thank you everything is working fine now when which to torch 2
