### ISSUE TITLE
tkinter.TclError: no display name and no $DISPLAY environment variable

### ISSUE THREAD

**Issue by RyanzW0521** [bmaltais/kohya_ss#1259]
when I was trying to train a lora and save a presets, this error occurred and any other command cannot run

anybody know how to fix it? I have update my tk-dev to the newest version

```
venv folder does not exist. Not activating...
10:23:54-452505 INFO     Version: v21.8.3                                         
10:23:54-460241 INFO     nVidia toolkit detected                                  
10:23:55-736912 INFO     Torch 2.0.1+cu118                                        
10:23:55-744866 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8700               
10:23:55-757092 INFO     Torch detected GPU: NVIDIA RTX A5000 VRAM 24256 Arch (8, 
                         6) Cores 64                                              
10:23:55-758768 INFO     Verifying modules instalation status from                
                         /kohya/kohya_ss/requirements_linux.txt...                
10:23:55-762635 INFO     Verifying modules instalation status from                
                         requirements.txt...                                      
10:23:58-142418 INFO     headless: False                                          
10:23:58-146753 INFO     Load CSS...                                              
Running on local URL:  http://127.0.0.1:7861

To create a public link, set `share=True` in `launch()`.
10:25:05-391457 INFO     Save as...                                               
Traceback (most recent call last):
  File "/root/miniconda3/envs/kohya/lib/python3.10/site-packages/gradio/routes.py", line 439, in run_predict
    output = await app.get_blocks().process_api(
  File "/root/miniconda3/envs/kohya/lib/python3.10/site-packages/gradio/blocks.py", line 1384, in process_api
    result = await self.call_function(
  File "/root/miniconda3/envs/kohya/lib/python3.10/site-packages/gradio/blocks.py", line 1089, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/root/miniconda3/envs/kohya/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/root/miniconda3/envs/kohya/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/root/miniconda3/envs/kohya/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/root/miniconda3/envs/kohya/lib/python3.10/site-packages/gradio/utils.py", line 700, in wrapper
    response = f(*args, **kwargs)
  File "/kohya/kohya_ss/lora_gui.py", line 173, in save_configuration
    file_path = get_saveasfile_path(file_path)
  File "/kohya/kohya_ss/library/common_gui.py", line 258, in get_saveasfile_path
    root = Tk()
  File "/root/miniconda3/envs/kohya/lib/python3.10/tkinter/__init__.py", line 2299, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable
```

**Comment by MZalfred** [comment]
The error message you encountered indicates that there is an issue with the Tkinter library, which is used for creating graphical user interfaces in Python. Specifically, the error is related to the display environment, which is not available when you are trying to run the code in a headless environment (e.g., on a server without a graphical interface).   
 give me a second let me think

**Comment by MZalfred** [comment]
Since LoRA GUI seems to rely on Tkinter for its graphical interface, running it in a headless environment could be the cause of the error. To fix this, you have a few options:

Use a GUI Environment: If possible, try running the code on a system with a graphical interface, such as your local machine or a remote desktop server. This way, the Tkinter library will have access to the required display environment, and the error should not occur.
Use Virtual Framebuffer (Xvfb): If running on a server without a graphical interface is a requirement, you can use a virtual framebuffer tool like Xvfb to provide a virtual display environment for the GUI. Xvfb creates a fake display server in memory, allowing you to run graphical applications without a physical display. Here's how you can do it:
First, install Xvfb on your server.
Then, before running your Python code, start Xvfb with a specific display number. For example, Xvfb :1 -screen 0 1024x768x24 &.
Set the $DISPLAY environment variable to point to the virtual display, like this: export DISPLAY=:1.
With this setup, your code should be able to access the virtual display created by Xvfb, and the Tkinter error should be resolved

**Comment by deepfriedheroin** [comment]
`10:23:58-142418 INFO     headless: False`

should work if set to `--headless`

**Comment by senpng** [comment]
E.g.: `xvfb-run ./gui.sh --share`

**Comment by RyanzW0521** [comment]
您的邮件我已收到，辛苦！
