### ISSUE TITLE
Can you add train UNET only option to the GUI

### ISSUE THREAD

**Issue by FurkanGozukara** [bmaltais/kohya_ss#1362]
For SDXL there is an alternative methodology for training 
This methodology requires training without text encoder

Can you add this option please? Thank you

**Comment by juanigsrz** [comment]
Man can't you open a simple PR and do it yourself instead of creating an issue for this? The functionality is already there

**Comment by etha302** [comment]
And also train text encoder option! Thanks

**Comment by bmaltais** [comment]
Please open the request direftly on kohya_ss sd-scripts repo in github. Once he add the option I will be able to support it.

**Comment by FurkanGozukara** [comment]
> Please open the request directly on kohya_ss sd-scripts repo in github. Once he add the option I will be able to support it.

sorry my bad

i thought that was available for SDXL too

I saw this code

https://github.com/kohya-ss/sd-scripts/blob/cf8021020f82398b3338019b72e15fe293863be6/train_network.py#L52

**Comment by FurkanGozukara** [comment]
hello @bmaltais 
this is the answer of [kohya-ss](https://github.com/kohya-ss) > https://github.com/bmaltais/kohya_ss/issues/1345

could you add clear options for both lora and fine tuning?

for lora - train only unet

for fine tuning of sdxl - train text encoder 

when i print command it really didn't add train text encoder to the fine tuning

**Comment by DarkAlchy** [comment]
Ahem, something pretty stupid here Bmalt because I use sdscripts on Colab for a long time before I purchased my 4090, and it already knows it unless something changed from my working pre SDXL sd-scripts and the post SDXL mess up that it is (at least for we ADA Nvidia card owners).

This has been available in the scripts since at least five months, if not longer.

![image](https://github.com/bmaltais/kohya_ss/assets/10561690/bdf8502d-d43f-467c-adac-1c141b48b24e)
