### ISSUE TITLE
Mutli_GPU config

### ISSUE THREAD

**Issue by shiftyjmusic** [bmaltais/kohya_ss#1410]
I can't get the training to work with multiple GPUs. I am training an SD 1.5 model on Dreambooth method.
I have checked if the system recognizes both GPUs with:

```
import torch
print(torch.cuda.device_count())
```
Result: 2

- I tried CUDA_VISIBLE_DEVICES=0,1 in gui.sh, no change.
- I tried CUDA_VISIBLE_DEVICES=all in gui.sh, failed.
- I tried --multi_gpu as a parameter but it wouldn't be recognized on training ending the script.

I am using the current RunPod Template.

How does it exactly work?

Would be much appreciated. Thank you!

**Comment by mrmeseeks23** [comment]
I have been using the 'accelerate config' command in the CLI (Jupyter Lab and/or web terminal) with intermittent success.  There are a lot of options to choose from and often it seems to run two instances in parallel instead of fractionating the data across the two or more GPU's.

The main settings I know work on RunPod are 1 machine and then it will ask how many GPU's when you would enter 2 (or more depending).  And then list all GPU's you would put 0,1,2,etc. depending on how many GPU's you re renting.

I am trying to figure out right now the optimal settings other than that.  DeepSpeed seems to work.  I have heard this is only really useful with lower VRAM availability though.  I am currently trying to sort through the Fully Sharded Data Parallel method but this is where I personally, am stuck.  TorchDynamo an dMegatron didn't seem to work.
I would love if a guide on utilizing multiple GPU's was posted with recommended settings, Deepspeed/FSDP settings specifically as this would be tremendously helpful outside of sifting through huggingfae's database which doesn't seem to give too much information specifically regardign kohya or other SD training modalities.

**Comment by upseem** [comment]
我也试过了，运行 accelerate config  gpu*2 运算，只是并行运行了两个运算，并没有将任务分割运算
