### ISSUE TITLE
LoHA SDXL - no way to continue Training 

### ISSUE THREAD

**Issue by CognitiveDiffusion** [bmaltais/kohya_ss#1522]
Hey there,

First off - thanks for all the work you guys are putting into this project.

I'm currently exploring LoHA as a way to "fine tune" XL without actually fine tuning the whole Model (which is horrendously slow).

In my case that means big-ish datasets, long training times and many Epochs.

That's why I tried to use the two ways to continue training from a LoRA - both of which don't work with LoHA.

When I input a LoHA-Checkpoint it gets discarded as "none" and has no effect on the training (starting from scratch).
When I create a Save State (16GB in size each time - would be great to specify that it only creates a save state whenever the training finishes or gets stopped, instead of as often as Models are saved) and try to load that for further training, my training crashes right away, because "1 argument was expected, but 3 arguments were given" (not at my machine, can't remember for what... something about weights?) .

I hope you can fix this. A way to stop and resume training properly is very important for ambitious projects.

Thank you.

**Comment by DevArqSangoi** [comment]
That 'None' you're seeing when loading a LoHa as weights doesn't actually mean it didn't load. I was having the same issue and was under the same impression; I even just posted about it here in the issues.

That 'None' is simply due to a lack of a 'return' statement in the load_weights function. Your LoHa is indeed being loaded. 

As for the save state, it's not worth it. I say this because before resolving the weights issue and confirming they were loading correctly, I tried using the save state feature. The script couldn't even load; it threw an error (in my case, it's LyCORIS for 1.5).
