### ISSUE TITLE
Steps maths, who is right?

### ISSUE THREAD

**Issue by GeneralAwareness** [bmaltais/kohya_ss#158]
Yours says 14 steps while Kohya says 16 so which is correct?  I started seeing the math being different and I am wondering what is Kohya doing that you aren't?

![image](https://user-images.githubusercontent.com/124339252/218371267-f98ac406-578f-442f-bcef-80c2b58f52ba.png)
![steps](https://user-images.githubusercontent.com/124339252/218371309-8d1e6b6f-e1da-46ed-acb2-34025f054fe8.png)

**Comment by bmaltais** [comment]
The kohya will always win over mine. Rounding is coursing this small difference. I have not bothered tracking down why as this usually result in harmless differences and does not impact the resulting model.

**Comment by GeneralAwareness** [comment]
See, I looked your math and his, and his is the most damn convoluted thing that I would have to really dig deep into to figure it out.  Immediately I spotted where you left out part of his equation, only I didn't go deep to see what that is.  If this LoRA had good math yours, and his, would be equal.

**Comment by bmaltais** [comment]
I agree... I also avoided tracing the math in kohya's code because I went
crossed yet trying to read it.

Mine is rather simple and to the point... And I have a feeling the
difference comes from the convoluted math in the trainer tools... But I
needed to do the match to provide the proper number of steps to fit within
an epoch... So even if our numbers are slightly different it sort of work
out at the end.

**Comment by GeneralAwareness** [comment]
Here is the thing it is not a small amount though as I just learned.  When I wrote this question originally to you, it was a small amount.

Max training steps:  534
Kohya's: 544

534*18=9612 vs 544*18=9792 so the total amount of step differences was 180.=, or a bit over 1.8 percent difference.
