### ISSUE TITLE
FR: training wheels from noobs like me (béquilles)

### ISSUE THREAD

**Issue by j2l** [bmaltais/kohya_ss#1753]
I'm patiently learning kohya (personally I'm around 2500s/it, my 3060 is around 2.5s/it) :smile: 
I compare JSON configuration file and sometimes hit a parameter I can't find in the GUI, like `train_on_input`.
Since I'm training a standard LORA, this parameter is not in the GUI, and I managed to find it in the code:
"train_on_input": ({"LyCORIS/iA3"}, gr.Checkbox),
So it's irrelevant to LORA, but still present in the parameters passed for LORA training, which leads me to ask myself: "But why?"

Since I'm a former designer (human-machine interface), I wonder if it wouldn't help to have the plain setting name near (or on hover) the plain name and also greyed checkboxes if not relevant, and also have only one parameter page, not "Basic" and "Advanced". Because CTRL+F is the only way to find your kitten in these 93 parameters.
Hope it makes sense.
Have a great day!

**Comment by bmaltais** [comment]
The application try to cater to every possible options for every possible LoRA modes… and as a result create a huge list of irrelevant parameters for types of LoRA that have no relation to them. Not pretty but only way I have coded it so far.

As far as combining basic and advanced in one page… it actually used to be like that and I split them apart because some users were complaining about the long list… I guess it does not please everyone. Not sur I want to work in an option to show them back in one page at this point.

**Comment by j2l** [comment]
Haha, I understand.
Thank you @bmaltais for taking the time to explain it to me.
