### ISSUE TITLE
Can Someone Help Me I am running it on Ubuntu server and remote it from a Mac but cant choose a file (model)!

### ISSUE THREAD

**Issue by alfi4000** [bmaltais/kohya_ss#1934]
Can Someone Help Me I am running it on Ubuntu server and remote it from a Mac but cant choose a file (model)!
I access it from the Mac over ip adress from the server!
Running on local URL:  http://0.0.0.0:7860

**Comment by emerth** [comment]
In your URL perhaps replace 0.0.0.0 with the IP address of your server.

**Comment by vhly** [comment]
Hi, you can't choose any file in remote PC.
Because:
1. kohya_ss written with Python script, and the choose file code with Python with Local GUI component;
2. kohya_ss server not accept file upload for file setting. so you can write your configuration to a json file.
3. all file path in web page please set to your ubuntu server path, not a mac or other pc path.

**Comment by alfi4000** [comment]
I'll try it the next few days it maybe works:
