### ISSUE TITLE
Non Zero Exit 

### ISSUE THREAD

**Issue by maryscary** [bmaltais/kohya_ss#1937]
17:02:23-241001 INFO     Start training LoRA Standard ...
17:02:23-241001 INFO     Checking for duplicate image filenames in training data directory...
17:02:23-241001 INFO     Valid image folder names found in: C:/Users/Quinn/Downloads/done/New folder
17:02:23-241001 INFO     Folder 100_SHIT: 121 images found
17:02:23-249509 INFO     Folder 100_SHIT: 12100 steps
17:02:23-249509 INFO     Total steps: 12100
17:02:23-250799 INFO     Train batch size: 2
17:02:23-250799 INFO     Gradient accumulation steps: 1
17:02:23-250799 INFO     Epoch: 1
17:02:23-250799 INFO     Regulatization factor: 1
17:02:23-250799 INFO     max_train_steps (12100 / 2 / 1 * 1 * 1) = 6050
17:02:23-250799 INFO     stop_text_encoder_training = 0
17:02:23-250799 INFO     lr_warmup_steps = 0
17:02:23-250799 INFO     Saving training config to C:/Users/Quinn/Downloads/done/outtpit\gfdzge_20240206-170223.json...
17:02:23-250799 INFO     accelerate launch --num_cpu_threads_per_process=2 "./train_network.py" --enable_bucket
                         --min_bucket_reso=256 --max_bucket_reso=2048
                         --pretrained_model_name_or_path="runwayml/stable-diffusion-v1-5"
                         --train_data_dir="C:/Users/Quinn/Downloads/done/New folder" --resolution="512,512"
                         --output_dir="C:/Users/Quinn/Downloads/done/outtpit"
                         --logging_dir="C:/Users/Quinn/Downloads/done/log" --network_alpha="128"
                         --save_model_as=safetensors --network_module=networks.lora --text_encoder_lr=5e-05
                         --unet_lr=0.0001 --network_dim=128 --output_name="gfdzge" --lr_scheduler_num_cycles="1"
                         --learning_rate="0.0001" --lr_scheduler="constant" --train_batch_size="2"
                         --max_train_steps="6050" --save_every_n_epochs="1" --mixed_precision="bf16"
                         --save_precision="bf16" --seed="1234" --caption_extension=".txt" --cache_latents
                         --optimizer_type="AdamW8bit" --max_grad_norm="1" --max_data_loader_n_workers="1" --clip_skip=2
                         --bucket_reso_steps=64 --xformers --bucket_no_upscale --noise_offset=0.0
A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
prepare tokenizer
Using DreamBooth method.
prepare images.
found directory C:\Users\Quinn\Downloads\done\New folder\100_SHIT contains 121 image files
12100 train images with repeating.
0 reg images.
no regularization images / 正則化画像が見つかりませんでした
[Dataset 0]
  batch_size: 2
  resolution: (512, 512)
  enable_bucket: True
  network_multiplier: 1.0
  min_bucket_reso: 256
  max_bucket_reso: 2048
  bucket_reso_steps: 64
  bucket_no_upscale: True

  [Subset 0 of Dataset 0]
    image_dir: "C:\Users\Quinn\Downloads\done\New folder\100_SHIT"
    image_count: 121
    num_repeats: 100
    shuffle_caption: False
    keep_tokens: 0
    keep_tokens_separator:
    caption_dropout_rate: 0.0
    caption_dropout_every_n_epoches: 0
    caption_tag_dropout_rate: 0.0
    caption_prefix: None
    caption_suffix: None
    color_aug: False
    flip_aug: False
    face_crop_aug_range: None
    random_crop: False
    token_warmup_min: 1,
    token_warmup_step: 0,
    is_reg: False
    class_tokens: SHIT
    caption_extension: .txt

[Dataset 0]
loading image sizes.
100%|██████████████████████████████████████████████████████████████████████████████| 121/121 [00:00<00:00, 5951.18it/s]
make buckets
min_bucket_reso and max_bucket_reso are ignored if bucket_no_upscale is set, because bucket reso is defined by image size automatically / bucket_no_upscaleが指定された場合は、bucketの解像度は画像サイズから自動計算されるため、min_bucket_resoとmax_bucket_resoは無視されます
number of images (including repeats) / 各bucketの画像枚数（繰り返し回数を含む）
bucket 0: resolution (512, 512), count: 12100
mean ar error (without repeats): 0.0
preparing accelerator
loading model for process 0/1
load Diffusers pretrained models: runwayml/stable-diffusion-v1-5
Loading pipeline components...: 100%|████████████████████████████████████████████████████| 5/5 [00:00<00:00, 17.95it/s]
You have disabled the safety checker for <class 'diffusers.pipelines.stable_diffusion.pipeline_stable_diffusion.StableDiffusionPipeline'> by passing `safety_checker=None`. Ensure that you abide to the conditions of the Stable Diffusion license and do not expose unfiltered results in services or applications open to the public. Both the diffusers team and Hugging Face strongly recommend to keep the safety filter enabled in all public facing circumstances, disabling it only for use-cases that involve analyzing network behavior or auditing its results. For more information, please have a look at https://github.com/huggingface/diffusers/pull/254 .
UNet2DConditionModel: 64, 8, 768, False, False
U-Net converted to original U-Net
Enable xformers for U-Net
import network module: networks.lora
[Dataset 0]
caching latents.
checking cache validity...
100%|████████████████████████████████████████████████████████████████████████████████████████| 121/121 [00:00<?, ?it/s]
caching latents...
  0%|                                                                                          | 0/121 [00:00<?, ?it/s]

its been getting stuck on catching latents but when it does load i get a non zero exit status and it stays like that for hours, no change, im not sure what the issue is, all my images are JPG and all 512 by 512, ive done this before and it worked just fine, im using a very large dataset but it worked before just fine

**Comment by Rojinski** [comment]
I have the same issue and I've tried all the solutions given in the different issue ports... And no, nothing works. No way fot training a TI or a Lora. 

`17:49:08-670078 INFO     Version: v22.6.0

17:49:08-677073 INFO     nVidia toolkit detected
17:49:09-938431 INFO     Torch 2.1.2+cu118
17:49:09-950716 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8700
17:49:09-951684 INFO     Torch detected GPU: NVIDIA GeForce RTX 3070 Ti VRAM 8192 Arch (8, 6) Cores 48
17:49:09-953415 INFO     Verifying modules installation status from requirements_windows_torch2.txt...
17:49:09-955048 INFO     Installing package: torch==2.1.2+cu118 torchvision==0.16.2+cu118 torchaudio==2.1.2+cu118
                         --index-url https://download.pytorch.org/whl/cu118
17:49:13-112668 INFO     Installing package: xformers==0.0.23.post1+cu118 --index-url
                         https://download.pytorch.org/whl/cu118
17:49:14-977479 INFO     Verifying modules installation status from requirements.txt...
17:49:14-980995 WARNING  Package wrong version: gradio 3.36.1 required 3.41.2
17:49:14-982273 INFO     Installing package: gradio==3.41.2
17:49:41-688306 INFO     headless: False
17:49:41-694341 INFO     Load CSS...
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
18:00:33-987459 INFO     Start training TI...
18:02:06-815645 INFO     Start training TI...
18:02:06-817646 INFO     Valid image folder names found in: E:\Images\AI\Training\Characters\Roji_Clover\images
18:02:06-818646 INFO     Folder 25_Roji_Clover: 3750 steps
18:02:06-819646 INFO     max_train_steps = 5000
18:02:06-820645 INFO     stop_text_encoder_training = 0
18:02:06-821645 INFO     lr_warmup_steps = 500
18:02:06-822645 INFO     Saving training config to
                         E:/Images/AI/Training/Characters/Roji_Clover/model\last_20240208-180206.json...
18:02:06-823646 INFO     accelerate launch --num_cpu_threads_per_process=2 "./train_textual_inversion.py"
                         --enable_bucket --min_bucket_reso=256 --max_bucket_reso=2048
                         --pretrained_model_name_or_path="runwayml/stable-diffusion-v1-5"
                         --train_data_dir="E:\Images\AI\Training\Characters\Roji_Clover\images" --resolution="768,768"
                         --output_dir="E:/Images/AI/Training/Characters/Roji_Clover/model"
                         --logging_dir="E:/Images/AI/Training/Characters/Roji_Clover/logs" --save_model_as=safetensors
                         --output_name="last" --lr_scheduler_num_cycles="10" --max_data_loader_n_workers="0"
                         --lr_scheduler="cosine" --lr_warmup_steps="500" --train_batch_size="1" --max_train_steps="5000"
                         --save_every_n_epochs="1" --mixed_precision="fp16" --save_precision="fp16"
                         --caption_extension=".txt" --cache_latents --optimizer_type="AdamW8bit"
                         --max_data_loader_n_workers="0" --bucket_reso_steps=64 --xformers --bucket_no_upscale
                         --noise_offset=0.0 --token_string="woman" --init_word="Roji_Clover" --num_vectors_per_token=12
                         --weights="E:/Images/AI/Training/Characters/Roji_Clover/model/Roji_Clover_main.json"
A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
prepare tokenizer
prepare accelerator
loading model for process 0/1
load Diffusers pretrained models: runwayml/stable-diffusion-v1-5
Loading pipeline components...: 100%|████████████████████████████████████████████████████| 5/5 [00:00<00:00, 11.31it/s]
You have disabled the safety checker for <class 'diffusers.pipelines.stable_diffusion.pipeline_stable_diffusion.StableDiffusionPipeline'> by passing `safety_checker=None`. Ensure that you abide to the conditions of the Stable Diffusion license and do not expose unfiltered results in services or applications open to the public. Both the diffusers team and Hugging Face strongly recommend to keep the safety filter enabled in all public facing circumstances, disabling it only for use-cases that involve analyzing network behavior or auditing its results. For more information, please have a look at https://github.com/huggingface/diffusers/pull/254 .
UNet2DConditionModel: 64, 8, 768, False, False
U-Net converted to original U-Net
token length for init words is not same to num_vectors_per_token, init words is repeated or truncated / 初期化単語のトークン長がnum_vectors_per_tokenと合わないため、繰り返しまたは切り捨てが発生します:  tokenizer 1, length 4
Traceback (most recent call last):
  File "F:\kohya_ss\train_textual_inversion.py", line 797, in <module>
    trainer.train(args)
  File "F:\kohya_ss\train_textual_inversion.py", line 225, in train
    num_added_tokens == args.num_vectors_per_token
AssertionError: tokenizer has same word to token string. please use another one / 指定したargs.token_stringは既に存在し ます。別の単語を使ってください: tokenizer 1, woman
Traceback (most recent call last):
  File "C:\Users\thier\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\thier\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "F:\kohya_ss\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "F:\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 47, in main
    args.func(args)
  File "F:\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 1017, in launch_command
    simple_launcher(args)
  File "F:\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 637, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['F:\\kohya_ss\\venv\\Scripts\\python.exe', './train_textual_inversion.py', '--enable_bucket', '--min_bucket_reso=256', '--max_bucket_reso=2048', '--pretrained_model_name_or_path=runwayml/stable-diffusion-v1-5', '--train_data_dir=E:\\Images\\AI\\Training\\Characters\\Roji_Clover\\images', '--resolution=768,768', '--output_dir=E:/Images/AI/Training/Characters/Roji_Clover/model', '--logging_dir=E:/Images/AI/Training/Characters/Roji_Clover/logs', '--save_model_as=safetensors', '--output_name=last', '--lr_scheduler_num_cycles=10', '--max_data_loader_n_workers=0', '--lr_scheduler=cosine', '--lr_warmup_steps=500', '--train_batch_size=1', '--max_train_steps=5000', '--save_every_n_epochs=1', '--mixed_precision=fp16', '--save_precision=fp16', '--caption_extension=.txt', '--cache_latents', '--optimizer_type=AdamW8bit', '--max_data_loader_n_workers=0', '--bucket_reso_steps=64', '--xformers', '--bucket_no_upscale', '--noise_offset=0.0', '--token_string=woman', '--init_word=Roji_Clover', '--num_vectors_per_token=12', '--weights=E:/Images/AI/Training/Characters/Roji_Clover/model/Roji_Clover_main.json']' returned non-zero exit status 1.`

It's been a while since I've trained TI and Lora with Koyha SS, so the problem could be... me. I hope you can help me... I used to train stuff without issues... I miss my "old" kohya (lol).

Have a beautiful day / evening / night and peace to you all.
