### ISSUE TITLE
Is it possible to queue up different training configurations?

### ISSUE THREAD

**Issue by Dashwii** [bmaltais/kohya_ss#1994]
Question in the title. Just want to know if it's possible so I can have different training configurations run back to back after finishing overnight. If so how do I do it?

**Comment by bmaltais** [comment]
Unfortunatly no, the GUI was not made for that.

**Comment by 5KilosOfCheese** [comment]
> Unfortunatly no, the GUI was not made for that.

Would this be possible though? Since we can save the parametres to a file, and the traning process from start to finish involves loading and unloading the model. Wouldn't it be possible to just create a UI feature in which we could load and execute the saved parametres? 

This is beyond my skills or realm of knowledge, HOWEVER I feel like all the elements are there.  The training finishing would just need a condition which calls the next one listen in the queue?  Obviously correct me if I am wrong. I only took one elective module of coding as part of my engineering degree.

**Comment by Dashwii** [comment]
> Unfortunatly no, the GUI was not made for that.

Ah unfortunate. Thank you anyways.
