### ISSUE TITLE
Problem with big white spaces when training own model

### ISSUE THREAD

**Issue by TheZaind** [bmaltais/kohya_ss#2019]
Problem with big white spaces when training own model
Hello,

I am currently training my own diffusion model. Everything is working fine, but when I use sounds smaller than 5 seconds (which means only a fraction of the training images is used), and I want to recreate it with my model, it fills the whole image instead of using, like in the original images, just a fraction. When converting to the sounds, it "sounds right," but it sounds just stretched. However, I want it to create the big white spaces as well. I am using over 1000 training images and trained over 500,000 iterations. Like I said, it "sounds right" to the prompt, but sounds stretched.

**Example training data images:**

![Afrobeat clap, key A#, rhythmic, lively, festive, 1](https://github.com/bmaltais/kohya_ss/assets/51163225/02777115-4ad9-483a-b8e2-593767f8ad77)

![EDM clap, , odyssey style, energetic, big, electronic - Kopie](https://github.com/bmaltais/kohya_ss/assets/51163225/930dda36-5169-470a-a58c-af00ad1a146c)

![Trap Clap, percussion, 808, energetic, modern, hiphop, 0](https://github.com/bmaltais/kohya_ss/assets/51163225/ce7b5052-71c4-44d2-ace6-05eadef0124f)

**Example generated images (who should look like the training images):**

![OSV2_StationV0 017_20240229064404_060000_02](https://github.com/bmaltais/kohya_ss/assets/51163225/2e947ce8-6b3d-4003-b9e3-adff8bf3c3ef)

![OSV2_StationV0 017_20240228232025_010000_02](https://github.com/bmaltais/kohya_ss/assets/51163225/1fc52b5c-c189-4d50-8f7d-329191938de6)

Any idea how I can fix this or what I'm doing wrong? I am using kohya_ss webUI for training.

Thanks! :)

**Comment by DKnight54** [comment]
I'm sorry if I misunderstood, but my understanding is that you'd like to train an audio model? I'm not sure that kohya_ss would be the correct script to use for training. As it is right now, kohya_ss is more built towards image training, and I think the issue you are describing is related to the fact that when generating an image, it's very difficult train and generate images with high contrast.

If your objective is to train to output audio, I ponder if looking into [training audio specific models ](https://github.com/Stability-AI/stable-audio-tools)might make more sense. 

Otherwise, the only thing I can imagine that might work, if you are saying that the "audio" images are correct, but stretched out, would be to adjust the image width to match the length, eg, if you generating 5 sec length, manual adjust the generation to however many horizontal pixels the 5 sec length is supposed to be.
