### ISSUE TITLE
Multi-GPU error

### ISSUE THREAD

**Issue by rmknyc** [bmaltais/kohya_ss#2050]
I am trying to train Kohya Dreambooth with 3 GPUs. 

Initially, I got an error after images were cached. It said "CUDA out of memory"

I then added "export CUDA_VISIBLE_DEVICES=0" to my launch command, and then I got a different error that wants me to use accelerate launch.

@FurkanGozukara 

![image](https://github.com/bmaltais/kohya_ss/assets/162852389/2d6816f2-e928-4f74-83a1-5eab6a39a5a7)
![image](https://github.com/bmaltais/kohya_ss/assets/162852389/4c01b1a8-af67-465f-84f1-5c3f8de0529d)

**Comment by bmaltais** [comment]
As much as I would like to help this is really much of a kohya_ss sd-scripts issue. I suggest you open a specific issue directly on kohya_ss sd-scripts repo about this one. If the GUI is missing an option to properly use the sd-scripts then I can step in... but I can't help with the sd-scripts code itself.

**Comment by storuky** [comment]
@rmknyc we are not able to run full finetune (sdxl_train.py) on 24 GB anymore even if follow Finetuning Resource Guide
... I faced same issue with `kohya_ss` repo. Pure sd-scripts is working good.

**Comment by bmaltais** [comment]
@storuky So if you run the command created Kohya_ss GUI in a dedicated sd-script repo it work? It is only failing when runniong through the GUI? Perhaps some of the more recent bitsandbytes modules are taking momre VRAM?

**Comment by storuky** [comment]
@bmaltais yes. Same command works different. kohya_ss falling with OOM on 24Gb while sd-scripts starting a finetuning well.
I tried to run from GUI – it's OOM, then printed command and run it manually in kohya_ss – OOM too. But when I run this command in sd-scripts – it's taking 23.75GiB and finetuning going well.
I don't use full bf16 training option because it has negative impact on small details training.

But anyway, I don't worry about it. @BootsofLagrangian added [DeepSpeed support](https://github.com/BootsofLagrangian/sd-scripts/tree/deepspeed) so now it's expanded the boundaries of what is possible: text encoder + unet training with batch size 7 on 3x4090 gpus 🤩  It would be cool to transfer this feature to the GUI.

**Comment by bmaltais** [comment]
When kohya add support for in in his sd-script repo the GUI should be able to use it.
