### ISSUE TITLE
ZeroDivisionError while saving the first epoch

### ISSUE THREAD

**Issue by kummetha** [bmaltais/kohya_ss#2135]
Using the latest pull from the repo and getting this error when the first epoch is being saved:

Traceback (most recent call last):
  File "/workspace/kohya_ss/sd-scripts/sdxl_train_network.py", line 184, in <module>
    trainer.train(args)
  File "/workspace/kohya_ss/sd-scripts/train_network.py", line 926, in train
    self.sample_images(accelerator, args, epoch + 1, global_step, accelerator.device, vae, tokenizer, text_encoder, unet)
  File "/workspace/kohya_ss/sd-scripts/sdxl_train_network.py", line 168, in sample_images
    sdxl_train_util.sample_images(accelerator, args, epoch, global_step, device, vae, tokenizer, text_encoder, unet)
  File "/workspace/kohya_ss/sd-scripts/library/sdxl_train_util.py", line 373, in sample_images
    return train_util.sample_images_common(SdxlStableDiffusionLongPromptWeightingPipeline, *args, **kwargs)
  File "/workspace/kohya_ss/sd-scripts/library/train_util.py", line 4789, in sample_images_common
    if epoch is None or epoch % args.sample_every_n_epochs != 0:
ZeroDivisionError: integer division or modulo by zero

Not sure what this error is. I picked number of epochs as 30 and max epochs is 30 as well

**Comment by bmaltais** [comment]
What does the actual command look like?

**Comment by bmaltais** [comment]
It is a bug in Kohya sd-script. Try settin the sample every n epoch to 1000… should help until the bug is fixed.

**Comment by S-Del** [comment]
@bmaltais
I set `Sample every n epochs` to 1000 in the "Samples" menu, and it went to 2 epochs.
Thank you very much for your prompt and accurate advice.
- ![image](https://github.com/bmaltais/kohya_ss/assets/52993483/dc33a1f1-359e-4ccf-b061-f553bf4795dc)
- ![image](https://github.com/bmaltais/kohya_ss/assets/52993483/f26f4b09-cbdd-46e8-8db9-c9a2c5d534ba)

Hopefully kummetha's error will be resolved as well.

**Comment by kummetha** [comment]
Thank you @bmaltais and @S-Del, this is working for me now

**Comment by S-Del** [comment]
I read the source to see why this `ZeroDivisionError` occurred. (なぜ今回の `ZeroDivisionError` が発生したのか、ソースを読みました。)
As it turns out, there seemed to be issues in both the GUI and kohya_ss code. (結論から書くと、GUI と kohya_ss の双方のコードに課題があるように思えました。)

The following is the relevant part of this Issue. (以下は今回の Issue の該当部分です。)
1. `class_sample_images.py`: Line 91
    ```py
    self.sample_every_n_epochs = gr.Number(
        label='Sample every n epochs',
        value=0, # int value
        precision=0,
        interactive=True,
    )
    ```
1. `class_sample_images.py`: Line 46
    ```py
    # if 0 == 0 == '0': False
    if sample_every_n_epochs == sample_every_n_steps == '0':
    return run_cmd
    ```
1. `class_sample_images.py`: Line 58
    ```py
    # if 0 != '0': True
    if sample_every_n_epochs != '0':
        run_cmd += f' --sample_every_n_epochs={sample_every_n_epochs}'
        # == run_cmd = ' --sample_every_n_epochs=0'
    ```
    - `log`
        ```
        06:02:34-469115 INFO accelerate launch...
                            ...
                            --sample_every_n_epochs=0 --sample_every_n_steps=0
        ```
1. `sd-script/library/train_util.py`: Line 3112
    ```py
    parser.add_argument(
        "--sample_every_n_epochs",
        type=int,
        default=None,
        help="...",
    )
    ```
1. `sd-script/library/train_util.py`: Line 4789
    ```py
    # if epoch is None or epoch % 0 != 0:
    # epoch % 0 is ZeroDivisionError
    if epoch is None or epoch % args.sample_every_n_epochs != 0:
        return
    ```

- In the GUI code, even if `0` is specified for `sample_every_n_epochs` and `sample_every_n_steps`, they are specified as options and executed. (GUI のコードでは、`sample_every_n_epochs` と `sample_every_n_steps` に `0` が指定されていてもオプションとして指定されて実行されてしまうこと。)
- In kohya_ss's code, the `%` operation is performed without checking if `0` is specified for `sample_every_n_epochs`. (kohya_ss のコードでは `sample_every_n_epochs` に `0` が指定されていないかチェックせずに `%` 演算を行っていること。)

These are the two points above. If they are to be corrected, I hope this will be helpful. (以上の 2 点です。もし修正されるのであれば参考になれば幸いです。)
Thanks for reading. (読んでくださってありがとうございます。)

**Comment by bmaltais** [comment]
The code for the GUI should have been fixed in the latest release. Are you using the latest release? The issue still exist in kohya's code...

**Comment by S-Del** [comment]
I just confirmed that it was updated two days ago.
![image](https://github.com/bmaltais/kohya_ss/assets/52993483/fb448fc5-6e96-40d9-b43b-3d7191bbe7c5)

My apologies for writing my comment without checking the new commit.
