### ISSUE TITLE
where to find documentation about the training theory behind the Lora Presets

### ISSUE THREAD

**Issue by rafstahelin** [bmaltais/kohya_ss#2177]
Hello, 

Trying to find the authors of the various Lora presets added by default in Kohya_ss. 
Would really help to get some background on how these settings benefit specific use cases

**Comment by bmaltais** [comment]
There is no documentation about those… there probably need to a major cleanup of those as some are quite old and probably useless… would be nice if there was a web site where users could share them… and download the ones they want to try.

**Comment by rafstahelin** [comment]
Yea, maybe criteria for displaying them is for a little presentation of what the settings do, and some insight on the main differences to basic settings. Would be useful to everyone

**Comment by 5KilosOfCheese** [comment]
> Yea, maybe criteria for displaying them is for a little presentation of what the settings do, and some insight on the main differences to basic settings. Would be useful to everyone

Issue is that depending on what optimiser you use, what LoRA type you use, the settings do different things. On top of this your have the optimiser args which change things a bit more (and aren't actually documented anywhere - far as I know - in relation to the training itself).

Example DAdaptAdam (My prefered method) works very differently to Prodigy, even though the kinda are related. I haven't been able to get Prodigy to work while I can get DAdaptAdam to work flawlessly. 

Another issue is that you can't be really sure why or how specific settings do things. If you throw in captions on top of this (and the fact that people don't caption in the same manner) it becomes basically impossible to figure out variables. 

And this is with the assumption that **everything is implement and working as intended in their papers.** 

I been slowly working my way through the settings, and effects from rank and dim on things by using a standard set of images. Even with same seed and tensorboard giving me basically similar curves the result can vary GREATLY. Trying to say how or what least of all why something changed - even if it is obvious that something did - is really hard. And it isn't a case of "better/worse" but fundamental differences in what the training ended up producing.

I have only just now started to understand basic standard LoRA and effect of captions. Something I'm actually thinking about writing a technical perspective on somewhere (I wonder if it could be added in to the UI as a guide/wiki entry?) because it would be easier to update. I'm not one to bother to make a youtube or some other irrelevant website post. It would be nice to have the information within a license and reach of peer-review.

I have noticed that trying to look for information about anything relating to training or LoRA (specifically), outside of the published papers and technical docs is useless. It is full of old-wifes tales, myths, "trust me bro" and just plain incorrect information.

I for one wouldn't mind to writing about certain aspects (which I have managed to understand and figure out). @bmaltais If such documentation was written - could it be added? I'm not even sure how I would request such addition as in the literal format (I'm not familliar with github and git). Because being an engineer and actually bothering to read the papers, I know that a lot of the answers are actually just there and citeable; and I quite good at simplifying it. But as I said earlier in this reply: there is a problem that we can only assume implementation and function is correct.

**Comment by bmaltais** [comment]
@5KilosOfCheese I could certainly add this as documentation in the repo for users to access in the GUI if you create it.

**Comment by 5KilosOfCheese** [comment]
> @5KilosOfCheese I could certainly add this as documentation in the repo for users to access in the GUI if you create it… you would need to learn the basic of doing Pull Request using git… but you can also simply publish them in your own repo and I could either point to the .md files or clone your repo in mine to have a copy within.

Great! I'll look into learning and figuring this out. It can't be harder than having to write documentation process and sheets for a whole machine shop... I hope. I'm sure we can figure something out.

**Comment by rafstahelin** [comment]
That is all true to a large extent. But certain presets work for large swaths of users in a specific use case. I for myself don't do anime, I focus on photographic persons, using datasets of about 10-30 datasets with a range of côoledity in the source images from highly convergent to highly creative (meaning very messy, harder to abstract). AdamW8bit, 128dim 64 alpha, Lr1-e4, etc but I'd love to experiment with Lykoris and other algo's like prodigy etc... but it would be a happy situation if the presets provided those extra arguments and perhaps some ideal basic settings within that implementation. A little descriptive preset name would lure people away from over generalising the specific settings. It is always the case in training that nothing is set. But a little updated templates section would be nice
