### ISSUE TITLE
Error when using Utilities/Caption images

### ISSUE THREAD

**Issue by Teskun** [bmaltais/kohya_ss#2223]
I just installed Kohya_ss (did not make any changers) ans its not working.
I wantend to use Utilities/ Caption Images and a got a Error because a module named triton is missing
![image](https://github.com/bmaltais/kohya_ss/assets/166338112/56992584-ae3b-410f-aaab-ee58f44ad612)

**Comment by bmaltais** [comment]
The triton error is actually not the reason. Not sure why it is failing… I will try to reproduce the issue at my end.

**Comment by bmaltais** [comment]
Look like the recent updates done to WD14 captionner in the sd-script latest release is causing things to fail... I will need to test what will make this work as I have the same issue as you at the moment... Might be a bug kohya will need to address in sd-scripts.

**Comment by bmaltais** [comment]
OK... look like you always have to enable `onyx` otherwise nothing work anymore... so I will make `onyx` checked by default.

I have taken the opportunity to add the missing GUI settings for the updates that were made to the wd14 tagger... it will be in the dev branch if you want to test it... I also added the v3 models to the list.

**Comment by Teskun** [comment]
Thanks for the quick Response!
I tried to train a lora and got the "same" answer that the Triton file is missing.
![Screenshot](https://github.com/bmaltais/kohya_ss/assets/166338112/cf29fc1b-b9c0-45ba-a2f0-9ee300a2f0d4)

**Comment by bmaltais** [comment]
The Triton error is, unfortunatly, normal on windows. It does not cause any issues and can be ignored.
