### ISSUE TITLE
[Feature Request] basic documentation for training options

### ISSUE THREAD

**Issue by ljleb** [bmaltais/kohya_ss#225]
I am relatively new to model training. I'd love to get a better understanding of what all the options do without having to try them all and figure how to get a good setup using trial and error. Would it be possible to open the wiki or put a link to a comprehensive guide in the readme?

I know there are links to videos on this software in the readme already, but they don't cover all the options or give any recommendation on what values to use.

**Comment by bmaltais** [comment]
Yeah... There need to be way better documentation... but I can ahrdly keep up with kohya_ss updates and me having fun training models... not enough hours in a day. Hopefully someone will create a PR or some documentation I can point to eventually... but I am starting to build some presets under the preset folder to help with some config examples for different trainers.

**Comment by SaltySkegg** [comment]
This fella has the best I have seen on youtube so far, it helped me out a lot since I barely know what I am doing too. - 

https://www.youtube.com/watch?v=7m522D01mh0&list=LL&index=1

**Comment by JS3910** [comment]
There are quite a lot of really good YouTube tutorials, and seeing things being done while they are described can be very educational. Unfortunately video content (especially 1-2 HOUR long YT videos) are completely useless as reference documentation since there's no way to find specific information even if you remember which of the dozens of nearly identically titled videos contain the information you are looking for. 

Probably the most annoying thing about SD right now is that almost all the most up-to-date knowledge is contained in two places which are not really indexed or indexable: youtube videos and discord channels. A source of relatively organized and searchable knowledge would be fantastic right about now.

**Comment by SaltySkegg** [comment]
Here is some experiential documentation on training loras i came across recently, might also be useful - https://rentry.org/59xed3#are-hypernetworks-useless-now
