### ISSUE TITLE
using xformers in lora training will cause the safetensors no effect in SD

### ISSUE THREAD

**Issue by trustmiao** [bmaltais/kohya_ss#318]
my setup is 3090 with following:
cuda_12.1.r12.1, torch-1.13.1+cu116-cp310-cp310-win_amd64.whl, xformers-0.0.16-cp310-cp310-win_amd64.whl

**if I train with xformers option checked, the trained lora will have no effect at all in SD.** 

when batch_size>1 there are also chances showing, following error while generating in SD:
`modules.devices.NansException: A tensor with all NaNs was produced in Unet. This could be either because there's not enough precision to represent the picture, or because your video card does not support half type. Try setting the "Upcast cross attention layer to float32" option in Settings > Stable Diffusion or using the --no-half commandline argument to fix this. Use --disable-nan-check commandline argument to disable this check.`

**if i train without xformers selected, everything will be just fine**

i tried also torch-1.13.1+cu117-cp310-cp310-win_amd64.whl,xformers-0.0.14.dev0-cp310-cp310-win_amd64.whl. doesn't help. 
btw, i just upgrade from 1080, which worked all well with 1080, with xformers option on, but suddenly stopped working after I changed gpu and upgraded nvidia drivers. 

the system is windows 10

**Comment by bmaltais** [comment]
I have seen someone reporting that installing xformers 0.16 solved this issue... I don't use the Linux version so I can't help much troubleshooting...

**Comment by trustmiao** [comment]
> 

can u share the link to the people's reports, though i tried 0.0.16 already, still not working

**Comment by Koronos** [comment]
> > 
> 
> can u share the link to the people's reports, though i tried 0.0.16 already, still not working

https://github.com/bmaltais/kohya_ss/issues/311

**Comment by trist4n** [comment]
just want to provide an update.
i will cautiously say i have got things working again on a 4090.

the issue is the card, the new architecture does not agree with older versions of pytorch.

what ive done is:

1: fresh clone of kohya_ss
2: install pytorch2 (cuda 11.8) nightly build, https://pytorch.org/get-started/locally/
3: followed this lovely persons instructions to build xformers, mixed with the instructions on sd-ui repo (install the same pytorch as above when building xformers, you can probably use the same venv but i didnt just incase):
https://github.com/kohya-ss/sd-scripts/discussions/111
https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Xformers
4: copy that xformers wheel file somewhere safe
5: back to kohya_ss, install our own rest of requirements as per instructions BUT install our own xformers wheel, pip install ./xformerstabtabtab

it *SEEMS* to work. I can train a Lora on a 4090 that actually does something.

**Comment by trustmiao** [comment]
you are the hero, going to give it a try

**Comment by devNegative-asm** [comment]
on my pip freeze, it's `torch==1.12.1+cu116` and xformers 0.0.14.dev0
and my driver is `Driver Version: 525.60.11    CUDA Version: 12.0`
last I tried on a 4090, which was like a couple days ago, it worked fine.

**Comment by rvkwi** [comment]
I ran into this as well, when moving my install between network drives (where i had to remake the venv but didn't update the system or pull changes in between). 
Still not sure what caused it, but without an obvious error i either got NaN at a certain point of training, or if it finished the LoRA behaved like it essentially learned nothing. All of this only happened if xformers was enabled.

After a lot of trial and error, the solution that worked for me was switching to the (at the time) most recent dev build on pip i could find

	(.venv) $ pip uninstall xformers
	(.venv) $ pip install xformers==0.0.17.dev473

This is on debian 11, 3090 with 525.60.13 driver and cuda 11.2.

**Comment by mrhelixx** [comment]
ERROR: Could not find a version that satisfies the requirement xformers==0.0.17.dev473 (from versions: 0.0.1, 0.0.2, 0.0.3, 0.0.4, 0.0.5, 0.0.6, 0.0.7, 0.0.8, 0.0.9, 0.0.10, 0.0.11, 0.0.12, 0.0.13, 0.0.16rc424, 0.0.16rc425, 0.0.16, 0.0.17rc481, 0.0.17rc482, 0.0.17, 0.0.18.dev502, 0.0.18.dev503, 0.0.18.dev504, 0.0.18, 0.0.19.dev505, 0.0.19.dev516)
ERROR: No matching distribution found for xformers==0.0.17.dev473

**Comment by rvkwi** [comment]
@mrhelixx

i just double checked thinking i had a typo but no this is the version i grabbed, 

```
(.venv) $ pip freeze | grep xformers
xformers==0.0.17.dev473
```

seems they removed it.
try one of the more recent (or close to this one) versions to see if they work https://pypi.org/project/xformers/#history
