### ISSUE TITLE
how to use random seed for sample?

### ISSUE THREAD

**Issue by tcflying** [bmaltais/kohya_ss#350]
i got error when i use prompt like:

a beautiful girl -w 640 -h 1280 -7 -s 16 -d -1

![image](https://user-images.githubusercontent.com/77509083/224387029-e822556a-a959-4213-985e-8a71f788f08c.png)

then will generate 512*512 pictures.

**Comment by DKnight54** [comment]
Not sure if it will fix the 512 by 512 issue, but from a quick scan of Kohya's code, it will default to random seed if there is no -d arguement. In other words? Instead of "a beautiful girl -w 640 -h 1280 -7 -s 16 -d -1", feed the sample generator "a beautiful girl -w 640 -h 1280 -7 -s 16". That's what I do.

As for the error message, I'm not sure it's related to your issue with the image size being stuck at 512x512, but it's saying that the version of DDIM scheduler that Kohya's including in the SD-scripts has incorrect configs. Since AFAIK, they are having the script automatically pull it from Hugging Face, either Hugging Face needs to do some changes, or maybe Kohya needs to amend their code to check if the checksums match for the current version, and pull new ones if there are any?

**Comment by tcflying** [comment]
thanks for the help, i removed -d, but the sample picture were still 512*512, if you working fine?

**Comment by bmaltais** [comment]
Use --w and --h to set the width and height
