### ISSUE TITLE
Render result in Automatic1111's WebUI significantly different

### ISSUE THREAD

**Issue by Loadus** [bmaltais/kohya_ss#421]
Just a quick question as I've been scratching my head with this for a couple of days. When I train a LoRA, the notebook renders out the test images and by the end of the training, the sample renders look 100% on what I'm after.

But then, rendering in Automatic1111's WebUI, the result is not even close, like, not even by a mile.

Sample image rendered by the python notebook during training >> https://i.imgur.com/Ra7W6ci.jpg
Another >> https://i.imgur.com/kwU3YeQ.jpg

They show that the model learned the trained style, they're 100% correct.

Then, in WebUI, the renders with the same prompt look like this >> https://i.imgur.com/PUTrVFU.jpg
And >> https://i.imgur.com/6WdzrtK.jpg

I tried disabling and enabling a lot of things, like xformers, medvram flag, vae, the LoCon extension etc. And still, the renders come out looking really really poor.

This is more of a WebUI issue, but I just thought I'd ask here on what the "mint" version is doing differently as it's getting such accurate renders out during training, but WebUI just renders out digital noise (some better results are obtained when changing the prompt to "_subject_ in \<lora:HRGigerArhPv3:1\> style" instead of just "_subject_ \<lora:HRGigerArhPv3:1\>", but still it's way off).

The model(s) are here >> https://civitai.com/models/20034

**Comment by bmaltais** [comment]
It might have to do with the chosen sampling method. Are you using the same sampling for both? kohya_ss implementation of sampling may also differ from auto1111 and produce different results. From experience I use the samples from the trainer just as a general gage for likeness... then I try the model in auto1111 and tweak the sampler to find the results with best likeness to the style I was after.

**Comment by Loadus** [comment]
I rendered the test images with Euler and used the same (and DPM++2M) in WebUI, but the rendering result looks like it's hitting some invisible barrier, I was thinking maybe not enough VRAM (8GB)?

Because the settings were identical and the only thing that is different is that the Colab is rendering it on a Tesla with 15GB vs my 1080, which might be the reason but still, it looks like some setting is just off or wrong in my WebUI setup and I can't figure out what. > . <

**Comment by michail935** [comment]
Hello, I have a question. I downloaded and installed Kohya's Stable Diffusion yesterday to train the model. But not from you, but also on githab, with a simpler installation. The question is, is there a folder "main\cudnn.zip" in your program, because when I downloaded it, Defender gave me that there is a file "Trojan:Win32/Casdet!rfn" in this folder. I have Windows 11 Pro and Defender did not miss this particular file, isolated it and then I deleted it. I'm asking because should I still trust the person who offered me to download that installation or do you have that folder where this file is? And I wonder if it's normal for trojans on githab?

**Comment by bmaltais** [comment]
I don't but I was referring to a zip file to get the file ... Now you got me worried ...

**Comment by bmaltais** [comment]
I ran a scan on the source I am pointing to and it comes clean. @michail935 do you get an error on that source?

**Comment by michail935** [comment]
Hello again. You misunderstood me. I wrote that I downloaded the same program, but not from you. They took, as I understand it, the original source and simplified it a bit. I had a question about the folder!!! Does your program have this folder - "main\cudnn.zip"? Is this folder "main\cudnn.zip" in the source? Is it normal that this folder is in kohya_ss?  I don't have any complaints against you?

**Comment by michail935** [comment]
You have this on GithHub: "Due to file size, I cannot post the DLLs needed for CUDNN 8.6 on Github. "That's why I thought there was no such folder in the original. I downloaded from someone else already with this folder, not you. And it was not empty.
I just think it's not good that someone is spreading Trojans on GitHub. К вам нет претензий.

**Comment by bmaltais** [comment]
> 

Indeed. Bad actors will take opportunities to push their stuff on people computers... always be on the lookout. But it could have been that the zip file I have been pointing to had been compromised... but it does not appear to be the case. 

I will need to see how I can get rid of that risk and replace the easy download with instructions on how to build it yourself...
