### ISSUE TITLE
size mismatch

### ISSUE THREAD

**Issue by thibaudart** [bmaltais/kohya_ss#479]
I launch a training, stop it and want to continue it.

I set the source model as the model of the latest epoch and the resume from saved training state to the latest state folder. Everyelse are similar.

I got this issue:

RuntimeError: Error(s) in loading state_dict for UNet2DConditionModel:
size mismatch for down_blocks.0.attentions.0.proj_in.weight: copying a param with shape torch.Size([320, 320]) from checkpoint, the shape in current model is torch.Size([320, 320, 1, 1]).
size mismatch for down_blocks.0.attentions.0.transformer_blocks.0.attn2.to_k.weight: copying a param with shape torch.Size([320, 1024]) from checkpoint, the shape in current model is torch.Size([320, 768]).
size mismatch for down_blocks.0.attentions.0.transformer_blocks.0.attn2.to_v.weight: copying a param with shape torch.Size([320, 1024]) from checkpoint, the shape in current model is torch.Size([320, 768]).

**Comment by bmaltais** [comment]
If you use the resume feature you should not need to change the source model to the latest saved epoch... as the resume will be loaded in memory anyway instead of the source model... Now... for this error I suspect it might be a bug in kohya_ss code. You should open an issue directly on his repo about it.

**Comment by thibaudart** [comment]
Thanks. 
i try to not change the source model and got similar issue. I ll see on kohya_ss repo.
