### ISSUE TITLE
Extracting Lora from Checkpoint on MacOS

### ISSUE THREAD

**Issue by shawncaple** [bmaltais/kohya_ss#488]
I know that Mac comparability is slowly rolling out but it appears that extracting a LORA from a Checkpoint is not working on MacOS. Anyone have the same issue? any workarounds? A Google Colab file maybe?

**Comment by runrgirl25** [comment]
Mine makes it all the way until the last step to save the extracted LORA, but then gives an error:

RuntimeError: File /Users/sara/stable-diffusion-webui/models/Lora cannot be opened.

It's odd because it's the folder path that I indicated for the "Save to" field.   But the script is behaving like it's looking for a file.

**Comment by runrgirl25** [comment]
I discovered a work around that seems to work:

1) Create an empty script file (I used Atom) and name it your output lora file.  (e.g. mylora.safetensors)
2) Place it into your Models/Lora folder
3) copy the path of the dummy lora file you just created and insert that into the <Save to> field in the GUI.

For some reason it's looking for an existing file to write to instead of creating a brand new file....

Haven't fully tested the results but seems to have worked.

**Comment by jstayco** [comment]
Is this to train a LoRa or is extracting one from a checkpoint a different operation? Sorry, I've never done this before because I only have the MacBook to work on and step one was to get this program working on it. 

And what tab/button is this happening with?

**Comment by 2blackbar** [comment]
its to extract lora from dreambooth model for example, you can then also additionally train on it to improve it
