### ISSUE TITLE
Problem with installation in windows

### ISSUE THREAD

**Issue by carlospum** [bmaltais/kohya_ss#546]
when i execute this in ther terminal

git clone https://github.com/bmaltais/kohya_ss.git
cd kohya_ss
setup.bat

i have a lot of errors when setup.bat tries to work. I tried to follow some youtube tutorials and the commands they are much more lines... What is the problem¿

**Comment by Ravath** [comment]
for starters, maybe you could provide a copy or a screenshot of the errors ?

**Comment by carlospum** [comment]
Yes, this is the errors

![image](https://user-images.githubusercontent.com/129921617/230067252-9cac3f69-2d94-4fb2-8ea7-8523d810310d.png)
![image](https://user-images.githubusercontent.com/129921617/230067308-06a5862c-2186-4bf6-b1ba-56c9d8963165.png)
![image](https://user-images.githubusercontent.com/129921617/230067354-9b4ae419-ab72-4e80-8d16-302c4c67dfa5.png)
![image](https://user-images.githubusercontent.com/129921617/230067380-0c42cfff-e127-457c-a8c4-36481bd4c1ed.png)
![image](https://user-images.githubusercontent.com/129921617/230067418-5f1778a8-0d66-4b92-a6f8-69404227fbf1.png)

**Comment by bmaltais** [comment]
Are you running python 3.10.9 installed as per the instructions?

**Comment by auroraTDunn** [comment]
I do not know about carlospum, but I'm getting the same error because the python that koyha installs in venv\scripts\ turns out to be 3.10.11. Thus if I run the either of the gui(_user_.bat scripts with the virtual env it will fail.

My plan for tomorrow is to go into the koyha scripts and check to make sure that when I rerun them freshly that it will install the 3.10.9 version instead of the latest 3.10.x.

**Comment by auroraTDunn** [comment]
OK, so it was totally on my end. I managed to change the order of my env vars so my 3.10.11 superseded  my other versions. One I changed the order Kohya runs fine.
Tunnelvision needed a nights rest!
