### ISSUE TITLE
macOs M2 -ERROR: No matching distribution found for tensorflow-macos==2.12.0

### ISSUE THREAD

**Issue by blee1001** [bmaltais/kohya_ss#563]
Could not find a version that satisfies the requirement tensorflow-macos==2.12.0 (from versions: none)
ERROR: No matching distribution found for tensorflow-macos==2.12.0

**Comment by littleyeson** [comment]
ERROR: Could not find a version that satisfies the requirement tensorflow-macos==2.12.0 (from versions: none)
ERROR: No matching distribution found for tensorflow-macos==2.12.0
Removing the temp requirements file.
Exiting Python virtual environment.
Copying accelerate config file to: /Users/yeson/.cache/huggingface/accelerate/default_config.yaml
Setup finished! Run ./gui.sh to start.

This plug-in is not found, which will affect the successful completion of the installation. Can I continue to use it?

**Comment by vkbest** [comment]
It's happening to me too

"F tensorflow/c/experimental/stream_executor/stream_executor.cc:808] Non-OK-status: stream_executor::MultiPlatformManager::RegisterPlatform( std::move(cplatform)) status: INTERNAL: platform is already registered with name: "METAL""

Because tensorflow-macos is not installed with the install script this error happens when I try to train a Lora

**Comment by jstayco** [comment]
You might also be on a non-apple silicon computer. In which case the regular tensorflow package should install I believe.

**Comment by jstayco** [comment]
如果你使用的是较旧的 Macbook，请尝试注释掉这些行并使用“tensorflow”。

**Comment by littleyeson** [comment]
> You might also be on a non-apple silicon computer. In which case the regular tensorflow package should install I believe.

My computer is M1.
