### ISSUE TITLE
Number of epochs halves when using regularization images.

### ISSUE THREAD

**Issue by mbastias** [bmaltais/kohya_ss#648]
Whenever I use regularization images my max number of epochs halves, if is an odd number it does a ceiling and goes for next int. The steps remain the same, so this makes really difficult to compare results against not using them. The training seems to still go ok.

Is that simple to reproduce, run a training without, look at the epoch number. Now run one with reg images and look at the epoch number.

**Comment by bmaltais** [comment]
This must be a side effect of the fact that regularisation images count toward the steps... So Kohya will need the number of steps be doubled when using regularisation images and as a result must be internally halving the epoch since more steps are required.

I can't fix this in the GUI and Kohya would need to fix is as part of his sd-script a. I suggest you raise this as an issue on his repo so he can address it there.

Then once he publish the fix I will integrate it in my repo.

**Comment by mbastias** [comment]
That's the weird part, I've been talking with people that use the scripts and they tell me the number doesn't change. I'd have to try with the scripts to see.
