### ISSUE TITLE
File Dialog not working

### ISSUE THREAD

**Issue by threadedblue** [bmaltais/kohya_ss#694]
I am using M1 Mac 13.3.1
I ran ./startup.sh
I start kohya_ss with ./gui.sh
The UI appears to function normally until it needs to interact with the file system.  I'm talking file select dialogs, save operations, et. al.  IOW If I click to open a file dialog, nothing happens.  The FD is not even hidden behind other windows.

Although I am not much of a python guy, I did run a little test to see if there was an issue with tkinter and there is not.  I can get an FC to popup.  It's only inside kohya_ss that the problem occurs.

As best I can tell, I found an example of the problem in common_gui.py right near line 158.

`def get_any_file_path(file_path=''):
    if not any(var in os.environ for var in ENV_EXCLUSION) and sys.platform != 'darwin':
        current_file_path = file_path`

Execution is not passing the if statement (above).  I can tell that "var" is not defined.  

Q: Am I missing something?  Did setup.sh fail me?

Thanks

**Comment by bmaltais** [comment]
Someone using linux and/or macos need to fix this. I don't use those platform so I can't really fix the Dialog issue on those platform. Somehow MacOS is a pain in the but when it comes to dealing with for UI and python.

**Comment by WingedWalrusLandingOnWater** [comment]
I'm having the same issue as of today!

 possibly somehow caused by whatever was going on with stable diffusion this morning??? it deleted like 300files when i loaded SD I spend a good hour sorting it all out to get SD working as it should then I come back to do some training on Kohya and I can't get the file system to load.

**Comment by threadedblue** [comment]
Thanks for the response.  Maybe I can fix.  Can you give me a clue as to the "var" that is not getting defined.  Where does it come from?  How should it be populated?

Thanks

**Comment by WingedWalrusLandingOnWater** [comment]
as of today mine is working as it should with no actions taken to correct it, IDK about the OP.

**Comment by amkurup** [comment]
Any update on this? I am still having this issue on MacOS (M1)

**Comment by andupotorac** [comment]
> 

Note that even if the file dialog doesn't work, you can still use it. Do this: copy the path of your config file (right click + option on the file in Finder), and add the path to the config, where you train lora in A1111.

Then, click load. Make any changes you need to it, click save (it does save, see Terminal), and then start Training.

So while we wait for a fix for the file picker, this should be a way to use the app in the meantime.

**Comment by abesmon** [comment]
@threadedblue execution is not passing because of `sys.platform != 'darwin'` (which checking if you have macOS). If you remove it, the code will proceed. BUT! It was placed here on purpose. Later in code there is a call to tkinter window creation, and if you remove `sys.platform != 'darwin'` will simply crash because tinter window creation can't be made on any thread different to Main (and we'r here not on main). So problem here is that window need to be created on main thread, but I think there is no easy solution for that :( (if there is one)
