### ISSUE TITLE
16xx loss=nan fix not implemented?

### ISSUE THREAD

**Issue by PaperOrb** [bmaltais/kohya_ss#722]
Currently experiencing this on my 1660ti 6gb card. Issue #436 mentioned a fix for 16xx cards experiencing loss=nan while training, but after talking with someone else about this, it seems like that issue was closed without the fix actually being implemented? I'll change the thread title to be for my specific issue if this fix was actually added. [Here's the gui sh output.](https://github.com/bmaltais/kohya_ss/files/11409832/gui_sh_output.txt). Here's my [json config](https://github.com/bmaltais/kohya_ss/files/11409848/config.txt) that was used during this.

**Comment by bmaltais** [comment]
I am not sure what the proposed fix is. I suspect this is something that will need to be supported by kohya's trainer to properly work.

Can you explain what the fix was? I saw something about enabling benchmark mode... This is something Kenya will need to address 1st in his code before I can support it in the GUI

**Comment by bmaltais** [comment]
Yeah... Something that Kohya will need to add to his code. Once he add it I will be able to it in the GUI...

**Comment by PaperOrb** [comment]
Thanks for the quick reply. I'll make an issue there in a bit and try to figure out if there's anything locally I can edit in the meantime so I can at least use this.
