### ISSUE TITLE
WTF ... Hate this new Koyha SS *fixed with help of the community*

### ISSUE THREAD

**Issue by trdahl** [bmaltais/kohya_ss#983]
My folder structure is correct, and still it gives me an error, it worked earlier today .. 

17:15:25-898825 ERROR    Not all images folders have proper name patterns in C:\Users\trdah\Pictures\Lora Training
                         Data\Actors\Daniel Craig\images. Please follow the folder structure documentation found at
                         docs\image_folder_structure.md ...

My folder structure is like:
50_(Name of the person)
                                       - image1
                                       - image1.txt
                                       
C:\Users\user\Pictures\Lora Training Data\Actors\Name of the actor\images\50_actors name

**Comment by bmaltais** [comment]
So inside the folder `C:\Users\trdah\Pictures\Lora Training
Data\Actors\Daniel Craig\images` you have a subfolder called `50_actors`

Is it the only thing in that folder? The `C:\Users\trdah\Pictures\Lora Training
Data\Actors\Daniel Craig\images` can only contain folders named like 50_actors`... nothing else... not even files can go there or it will choke.

**Comment by GoganJ** [comment]
Same issue with me. Folder structure seems correct. I have done this many times but now doesn't seem to recognize folder strcuture. This is the 3rd mention in the last 24hrs, is this GUI error or user error..?

--- images
------ 100_Name
---------- image1.png
---------- image1.txt]

**Comment by lanthos** [comment]
howdy!  This comes up when trying to run this on a Mac since Mac OS by default installs a hidden file named .DS_store inside of every folder.  Looking through the code it looks like you only care about the folders being named the same so I made a local change and everything's working fine on my machine:

`if len(matching_subfolders) != len(os.listdir(folder_path)):`

became

`if len(matching_subfolders) != len([item for item in os.listdir(folder_path) if os.path.isdir(os.path.join(folder_path, item))]):`

If you're only looking for folders you might consider that change (happy to make a PR if you would like but that should be easy enough to update and confirm working).  For anyone who is running across this, make sure you have your finder/explorer window allowing you to see hidden files and folders and make sure there isn't an extra file in there you don't expect.  

Hope that helps!

**Comment by swamp-cabbage** [comment]
I have been using Kohya_ss for two months without issue, utilizing /images/20_face file structure (selecting the "images" folder as "image folder" in the GUI. 

I am receiving the "not all images folders have proper name pattern..." error message as described above.

Any idea what has changed since last update, and what needs to be changed on my end to make it work (in Windows) ?

Thanks !

**Comment by AndrewDrimer** [comment]
create  this> 100_Simple>Images>100_Simple>
[https://ibb.co/TvG1GRC](url) work

**Comment by bmaltais** [comment]
Hummm... dans MacOS hidden files... I will add a rule to ignore dot files in the code...

**Comment by bmaltais** [comment]
I have pushed an updated version to the dev2 branch if you want to test it.

**Comment by swamp-cabbage** [comment]
I may have cried wolf. I renamed my image files in Windows using f2 and they all have parentheses in file name (like 001(1).jpg). I think it choked on that, as it was OK with a different bunch of files. 

Thanks for looking at it though !

**Comment by mkrd** [comment]
> create this> 100_Simple>Images>100_Simple> https://ibb.co/TvG1GRC work

I have the same issue, but this worked for me

**Comment by msampson3d** [comment]
It breaks on windows for a related reason. Windows creates a hidden 'deskstop.ini' file in the directory. I think I see what was attempted here. They're trying to make sure every folder fits the pattern, as a folder that didn't could cause errors. The problem is the check is being done against things that are not folders. 

Wouldn't a better solution be to check if the 'file' was a directory before comparing the length?

So in commn_gui.py

line 1305 from
```
    # Check if all sub-folders match the pattern
    filenames = [filename for filename in os.listdir(folder_path) if not filename.startswith('.')]
    if len(matching_subfolders) != len(filenames):
        log.error(f"Not all image folders have proper name patterns <numbre>_<text> in {folder_path}. Please follow the folder structure documentation found at docs/image_folder_structure.md ...")
        log.error(f"Only folders are allowed in {folder_path}...")
        return False
```

To:
```
    # Check if all sub-folders match the pattern
    filenames = [filename for filename in os.listdir(folder_path) if os.path.isdir(os.path.join(folder_path, filename))]
    if len(matching_subfolders) != len(filenames):
        log.error(f"Not all image folders have proper name patterns <numbre>_<text> in {folder_path}. Please follow the folder structure documentation found at docs/image_folder_structure.md ...")
        log.error(f"Only folders are allowed in {folder_path}...")
        return False
```

I get wanting to help people figure out that they put their training images in the root folder, but I don't think the current implementation is the way.

I'll submit a pull request for the change later if nobody is currently working on it.  Trying to anticipate all the specific files to ignore doesn't seem right.

**Comment by bmaltais** [comment]
The whole check code could be better... Ultimately I am trying to avoid issues where people don't use the appropriate folder structure... But I guess I am causing another issue in the process. Heh

**Comment by mkrd** [comment]
Just as a short note, this is also happening on Linux for me, so the underlying issue might not be related to the hidden files

**Comment by bmaltais** [comment]
Maybe I will change the code for now to a warning only... And let the execution continue. Maybe I will find the time to write a better folder structure validation function...

**Comment by bmaltais** [comment]
I have pushed a temporary fix to the dev2 branch if you want to try it. It will only report and continue none the less... but at least it will warn the user of a possible issue with the dataset.

**Comment by mkrd** [comment]
@bmaltais Nice, thanks! I also think it would be a good idea to revert it on the main branch to a warning. Kohya SS is an extremely popular tool, so there might be thousands of people wondering why they can't get it to run

**Comment by bmaltais** [comment]
I will take a pull request to change those if you care to contribute a better color scheme.

**Comment by bobpuffer1** [comment]
Forgive me -- all I needed to do was change my window profile in Terminal

**Comment by Jimbohhh** [comment]
I had this same issue on the mac I had to open a new terminal window change directory to the image folder and then run 

find . -name '.DS_Store' -type f -delete

**Comment by yousonnet** [comment]
> create this> 100_Simple>Images>100_Simple> https://ibb.co/TvG1GRC work

don't know the reason,but this worked for me ,thx!
